#!/usr/bin/env node
/**
 * Bot: Test Generator Agent
 * Automatically generates tests for code changes following TDD principles
 */

const GITLAB_TOKEN = process.env.GITLAB_TOKEN || '';
const GITLAB_URL = process.env.GITLAB_URL || 'https://gitlab.com/api/v4';
const PROJECT_ID = process.env.CI_PROJECT_ID || process.env.GITLAB_PROJECT_ID || '';
const MR_IID = process.env.CI_MERGE_REQUEST_IID || '';

interface TestFile {
  path: string;
  content: string;
  type: 'unit' | 'integration' | 'e2e';
}

async function getMRChanges(): Promise<any[]> {
  const response = await fetch(`${GITLAB_URL}/projects/${PROJECT_ID}/merge_requests/${MR_IID}/changes`, {
    headers: {
      'Authorization': `Bearer ${GITLAB_TOKEN}`,
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch MR changes: ${response.statusText}`);
  }

  const data = await response.json();
  return data.changes || [];
}

function generateUnitTest(filePath: string, code: string): TestFile | null {
  if (!filePath.endsWith('.ts') && !filePath.endsWith('.js')) {
    return null;
  }

  const testPath = filePath
    .replace(/^src\//, 'tests/unit/')
    .replace(/\.ts$/, '.test.ts')
    .replace(/\.js$/, '.test.js');

  const functionMatches = code.matchAll(/(?:export\s+)?(?:async\s+)?function\s+(\w+)/g);
  const functions = Array.from(functionMatches).map(m => m[1]);

  if (functions.length === 0) {
    return null;
  }

  const testContent = `/**
 * Tests for ${filePath}
 * Generated by bot-test-generator
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { ${functions.join(', ')} } from '../${filePath.replace(/^tests\/unit\//, 'src/').replace(/\.test\.ts$/, '.ts')}';

describe('${filePath}', () => {
${functions.map(fn => `  it('should test ${fn}', () => {
    assert.ok(true);
  });`).join('\n\n')}
});
`;

  return {
    path: testPath,
    content: testContent,
    type: 'unit'
  };
}

async function createTestFile(testFile: TestFile): Promise<boolean> {
  const response = await fetch(`${GITLAB_URL}/projects/${PROJECT_ID}/repository/files/${encodeURIComponent(testFile.path)}`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GITLAB_TOKEN}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      branch: process.env.CI_MERGE_REQUEST_SOURCE_BRANCH_NAME || 'main',
      content: Buffer.from(testFile.content).toString('base64'),
      encoding: 'base64',
      commit_message: `test: add ${testFile.type} tests for ${testFile.path}`
    })
  });

  return response.ok;
}

async function postComment(generated: number, errors: string[]): Promise<void> {
  let comment = '## 🧪 Test Generation Results\n\n';
  comment += `✅ Generated ${generated} test files\n`;

  if (errors.length > 0) {
    comment += `\n⚠️ Errors:\n`;
    errors.forEach(err => comment += `- ${err}\n`);
  }

  await fetch(`${GITLAB_URL}/projects/${PROJECT_ID}/merge_requests/${MR_IID}/notes`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GITLAB_TOKEN}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ body: comment })
  });
}

async function generateTests(): Promise<void> {
  if (!GITLAB_TOKEN || !PROJECT_ID || !MR_IID) {
    throw new Error('GITLAB_TOKEN, PROJECT_ID, and MR_IID are required');
  }

  console.log(`Generating tests for MR !${MR_IID}...`);

  const changes = await getMRChanges();
  const testFiles: TestFile[] = [];
  const errors: string[] = [];

  for (const change of changes) {
    if (change.deleted_file || !change.new_path) {
      continue;
    }

    if (change.new_path.includes('test') || change.new_path.includes('spec')) {
      continue;
    }

    const content = change.diff || '';
    const testFile = generateUnitTest(change.new_path, content);

    if (testFile) {
      testFiles.push(testFile);
    }
  }

  let generated = 0;
  for (const testFile of testFiles) {
    try {
      const success = await createTestFile(testFile);
      if (success) {
        generated++;
        console.log(`✅ Generated ${testFile.path}`);
      } else {
        errors.push(`Failed to create ${testFile.path}`);
      }
    } catch (error) {
      errors.push(`${testFile.path}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  await postComment(generated, errors);

  console.log(`\n✅ Generated ${generated}/${testFiles.length} test files`);
}

if (require.main === module) {
  generateTests().catch(error => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

export { generateTests };
