/**
 * WorkspaceService — Init, discover, status for OSSA workspaces
 *
 * Extracts handleWorkspace logic from MCP server. No TUI/HTTP deps.
 */

import fg from 'fast-glob';
import { injectable } from 'inversify';
import yaml from 'js-yaml';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { IdentityService } from '../identity/identity.service.js';

export interface WorkspaceInitResult {
  action: 'init';
  status: 'created' | 'already_exists';
  path: string;
  name?: string;
}

export interface WorkspaceScaffoldResult {
  action: 'scaffold';
  status: 'completed';
  workspacePath: string;
  projectsScaffolded: number;
  codeWorkspacePath: string;
  externalWorktreesBound: number;
}

export interface DiscoveryAgent {
  name: string;
  path: string;
  version: string;
  kind: string;
  description: string;
}

export interface DiscoveryResult {
  action: 'discover';
  count: number;
  agents: DiscoveryAgent[];
}

export interface WorkspaceStatus {
  action: 'status';
  initialized: boolean;
  workspace?: Record<string, unknown>;
  message?: string;
}

@injectable()
export class WorkspaceService {
  async init(directory: string, name?: string): Promise<WorkspaceInitResult> {
    const dir = path.resolve(directory);
    const wsDir = path.join(dir, '.agents-workspace');
    const registryDir = path.join(wsDir, 'registry');

    if (fs.existsSync(wsDir)) {
      return { action: 'init', status: 'already_exists', path: wsDir };
    }

    fs.mkdirSync(registryDir, { recursive: true });
    const wsName = name || path.basename(dir);
    const indexYaml = yaml.dump({
      workspace: wsName,
      version: '1.0.0',
      created: new Date().toISOString(),
      agents: [],
    });
    fs.writeFileSync(path.join(registryDir, 'index.yaml'), indexYaml);
    fs.writeFileSync(
      path.join(wsDir, 'README.md'),
      `# OSSA Workspace: ${wsName}\n\nGenerated by OSSA.\n\nRun \`ossa workspace discover\` to scan for agents.\n`
    );

    return { action: 'init', status: 'created', path: wsDir, name: wsName };
  }

  async scaffold(
    baseDirectory: string,
    initProjects: string[] = [],
    externalWorktrees: string[] = []
  ): Promise<WorkspaceScaffoldResult> {
    const dir = path.resolve(baseDirectory);
    const wsDir = path.join(dir, '.agents-workspace');

    // 1. Ensure the agents-workspace orchestrator root exists
    if (!fs.existsSync(wsDir)) {
      await this.init(dir);
    }

    // 2. Deliberate provisioning: Only inject .agents/ folders into explicitly specified projects
    const projectsScaffolded: string[] = [];
    for (const projectPath of initProjects) {
      const pDir = path.resolve(dir, projectPath);
      if (fs.existsSync(pDir)) {
        const agentsDir = path.join(pDir, '.agents');
        if (!fs.existsSync(agentsDir)) {
          fs.mkdirSync(agentsDir, { recursive: true });
          
          const identity = IdentityService.provisionIdentityForAgent(pDir);

          const stubYaml = yaml.dump({
            apiVersion: 'agents.bluefly.io/v1alpha1',
            kind: 'Agent',
            metadata: { 
              name: path.basename(pDir), 
              version: '0.1.0',
              identity: {
                publicKey: identity.publicKey,
                algorithm: identity.algorithm
              }
            },
            spec: { capabilities: [] },
          });
          fs.writeFileSync(
            path.join(agentsDir, 'manifest.ossa.yaml'),
            stubYaml
          );
          projectsScaffolded.push(path.basename(pDir));
        }
      }
    }

    // 3. Generate the IDE multi-root workspace file dynamically using discover()
    const codeWorkspacePath = path.join(
      dir,
      'agents-playground.code-workspace'
    );
    const folders: Array<{ name: string; path: string }> = [
      { name: '⚙️ Agents Workspace Root', path: wsDir },
    ];

    // Scan base directory for agent projects using the advanced globber in discover()
    const baseDiscovery = await this.discover(dir);
    const discoveredDirs = new Set<string>();
    for (const agent of baseDiscovery.agents) {
      // agent.path is inside .agents/, we want the project root
      const pRoot = path.dirname(path.dirname(agent.path));
      if (!discoveredDirs.has(pRoot) && pRoot !== dir && pRoot !== wsDir) {
        discoveredDirs.add(pRoot);
        folders.push({ name: `🤖 ${path.basename(pRoot)}`, path: pRoot });
      }
    }

    // Bind requested external git worktrees or arbitrary paths to the IDE
    const worktreesBound: string[] = [];
    for (const wtPath of externalWorktrees) {
      const wDir = path.resolve(wtPath);
      if (fs.existsSync(wDir)) {
        folders.push({
          name: `🌳 ${path.basename(wDir)} (Worktree)`,
          path: wDir,
        });
        worktreesBound.push(wDir);

        // Also run a discovery in the worktree to add it to the central workspace registry
        const wtDiscovery = await this.discover(wDir);
        for (const agent of wtDiscovery.agents) {
          const pRoot = path.dirname(path.dirname(agent.path));
          if (!discoveredDirs.has(pRoot)) {
            discoveredDirs.add(pRoot);
            folders.push({ name: `🤖 ${path.basename(pRoot)}`, path: pRoot });
          }
        }
      }
    }

    const vscodeSettings = {
      'files.exclude': {
        '**/node_modules': true,
        '**/.git': true,
        '**/dist': true,
      },
      'kiroAgent.configureMCP': 'Enabled',
    };

    fs.writeFileSync(
      codeWorkspacePath,
      JSON.stringify({ folders, settings: vscodeSettings }, null, 2)
    );

    return {
      action: 'scaffold',
      status: 'completed',
      workspacePath: wsDir,
      projectsScaffolded: projectsScaffolded.length,
      codeWorkspacePath,
      externalWorktreesBound: worktreesBound.length,
    };
  }

  async discover(directory: string): Promise<DiscoveryResult> {
    const dir = path.resolve(directory);
    const patterns = [
      '**/*.ossa.yaml',
      '**/*.ossa.yml',
      '**/.agents/*/manifest.ossa.yaml',
    ];
    const ignorePatterns = [
      '**/node_modules/**',
      '**/dist/**',
      '**/.git/**',
      '**/coverage/**',
    ];
    const files = await fg(patterns, {
      cwd: dir,
      ignore: ignorePatterns,
      absolute: true,
    });

    const agents: DiscoveryAgent[] = [];
    for (const f of files) {
      try {
        const raw = fs.readFileSync(f, 'utf8');
        const m = yaml.load(raw) as Record<string, unknown>;
        const meta = m?.metadata as Record<string, unknown> | undefined;
        agents.push({
          name: (meta?.name as string) || path.basename(path.dirname(f)),
          path: f,
          version: (meta?.version as string) || '0.0.0',
          kind: (m?.kind as string) || 'Agent',
          description: (meta?.description as string) || '',
        });
      } catch {
        // Skip unparseable files
      }
    }

    // Write discovery output if .agents-workspace exists
    const wsDir = path.join(dir, '.agents-workspace');
    if (fs.existsSync(wsDir)) {
      const registryDir = path.join(wsDir, 'registry');
      fs.mkdirSync(registryDir, { recursive: true });
      const index = {
        workspace: path.basename(dir),
        discovered: new Date().toISOString(),
        count: agents.length,
        agents: agents.map((a) => ({
          name: a.name,
          version: a.version,
          kind: a.kind,
          path: a.path,
        })),
      };
      fs.writeFileSync(path.join(registryDir, 'index.yaml'), yaml.dump(index));
    }

    return { action: 'discover', count: agents.length, agents };
  }

  async status(directory: string): Promise<WorkspaceStatus> {
    const dir = path.resolve(directory);
    const wsDir = path.join(dir, '.agents-workspace');
    const indexPath = path.join(wsDir, 'registry', 'index.yaml');

    if (!fs.existsSync(indexPath)) {
      return {
        action: 'status',
        initialized: false,
        message: 'Run ossa workspace init first',
      };
    }

    const indexContent = yaml.load(
      fs.readFileSync(indexPath, 'utf8')
    ) as Record<string, unknown>;
    return { action: 'status', initialized: true, workspace: indexContent };
  }
}
