/**
 * WorkspaceService — Init, discover, status for OSSA workspaces
 *
 * Extracts handleWorkspace logic from MCP server. No TUI/HTTP deps.
 */

import { injectable } from 'inversify';
import * as fs from 'node:fs';
import * as path from 'node:path';
import yaml from 'js-yaml';
import fg from 'fast-glob';

export interface WorkspaceInitResult {
  action: 'init';
  status: 'created' | 'already_exists';
  path: string;
  name?: string;
}

export interface DiscoveryAgent {
  name: string;
  path: string;
  version: string;
  kind: string;
  description: string;
}

export interface DiscoveryResult {
  action: 'discover';
  count: number;
  agents: DiscoveryAgent[];
}

export interface WorkspaceStatus {
  action: 'status';
  initialized: boolean;
  workspace?: Record<string, unknown>;
  message?: string;
}

@injectable()
export class WorkspaceService {
  async init(directory: string, name?: string): Promise<WorkspaceInitResult> {
    const dir = path.resolve(directory);
    const wsDir = path.join(dir, '.agents-workspace');
    const registryDir = path.join(wsDir, 'registry');

    if (fs.existsSync(wsDir)) {
      return { action: 'init', status: 'already_exists', path: wsDir };
    }

    fs.mkdirSync(registryDir, { recursive: true });
    const wsName = name || path.basename(dir);
    const indexYaml = yaml.dump({
      workspace: wsName,
      version: '1.0.0',
      created: new Date().toISOString(),
      agents: [],
    });
    fs.writeFileSync(path.join(registryDir, 'index.yaml'), indexYaml);
    fs.writeFileSync(
      path.join(wsDir, 'README.md'),
      `# OSSA Workspace: ${wsName}\n\nGenerated by OSSA.\n\nRun \`ossa workspace discover\` to scan for agents.\n`
    );

    return { action: 'init', status: 'created', path: wsDir, name: wsName };
  }

  async discover(directory: string): Promise<DiscoveryResult> {
    const dir = path.resolve(directory);
    const patterns = ['**/*.ossa.yaml', '**/*.ossa.yml', '**/.agents/*/manifest.ossa.yaml'];
    const ignorePatterns = ['**/node_modules/**', '**/dist/**', '**/.git/**', '**/coverage/**'];
    const files = await fg(patterns, { cwd: dir, ignore: ignorePatterns, absolute: true });

    const agents: DiscoveryAgent[] = [];
    for (const f of files) {
      try {
        const raw = fs.readFileSync(f, 'utf8');
        const m = yaml.load(raw) as Record<string, unknown>;
        const meta = m?.metadata as Record<string, unknown> | undefined;
        agents.push({
          name: (meta?.name as string) || path.basename(path.dirname(f)),
          path: f,
          version: (meta?.version as string) || '0.0.0',
          kind: (m?.kind as string) || 'Agent',
          description: (meta?.description as string) || '',
        });
      } catch {
        // Skip unparseable files
      }
    }

    // Write discovery output if .agents-workspace exists
    const wsDir = path.join(dir, '.agents-workspace');
    if (fs.existsSync(wsDir)) {
      const registryDir = path.join(wsDir, 'registry');
      fs.mkdirSync(registryDir, { recursive: true });
      const index = {
        workspace: path.basename(dir),
        discovered: new Date().toISOString(),
        count: agents.length,
        agents: agents.map((a) => ({ name: a.name, version: a.version, kind: a.kind, path: a.path })),
      };
      fs.writeFileSync(path.join(registryDir, 'index.yaml'), yaml.dump(index));
    }

    return { action: 'discover', count: agents.length, agents };
  }

  async status(directory: string): Promise<WorkspaceStatus> {
    const dir = path.resolve(directory);
    const wsDir = path.join(dir, '.agents-workspace');
    const indexPath = path.join(wsDir, 'registry', 'index.yaml');

    if (!fs.existsSync(indexPath)) {
      return { action: 'status', initialized: false, message: 'Run ossa workspace init first' };
    }

    const indexContent = yaml.load(fs.readFileSync(indexPath, 'utf8')) as Record<string, unknown>;
    return { action: 'status', initialized: true, workspace: indexContent };
  }
}
