import * as yaml from 'js-yaml';
import { OSSAManifest, Skill } from '../validators/manifest.validator';

export class SkillGenerator {
  /**
   * Generate SKILL.md from OSSA manifest and skill name
   */
  generate(manifest: OSSAManifest, skillName: string): string {
    const skill = manifest.skills?.find((s) => s.name === skillName);

    if (!skill) {
      throw new Error(`Skill "${skillName}" not found in manifest`);
    }

    // Build frontmatter
    const frontmatter = {
      name: skill.name,
      version: manifest.metadata.version,
      description: skill.description,
      author: manifest.metadata.author,
      license: manifest.metadata.license,
      trigger: skill.trigger,
      parameters: skill.parameters,
      tags: manifest.metadata.tags,
    };

    // Remove undefined values
    Object.keys(frontmatter).forEach((key) => {
      if (frontmatter[key as keyof typeof frontmatter] === undefined) {
        delete frontmatter[key as keyof typeof frontmatter];
      }
    });

    const frontmatterYaml = yaml.dump(frontmatter, {
      indent: 2,
      lineWidth: 80,
      noRefs: true,
    });

    // Build body
    const body = this.generateBody(manifest, skill);

    return `---\n${frontmatterYaml}---\n\n${body}`;
  }

  private generateBody(manifest: OSSAManifest, skill: Skill): string {
    let body = `# ${skill.name}\n\n`;
    body += `${skill.description}\n\n`;

    // Agent capabilities
    body += `## Agent Capabilities\n\n`;
    body += `This skill is part of a **${manifest.agent.type}** agent with the following capabilities:\n\n`;
    manifest.agent.capabilities.forEach((cap) => {
      body += `- ${cap}\n`;
    });
    body += `\n`;

    // Usage
    body += `## Usage\n\n`;
    if (skill.trigger.type === 'slash_command') {
      body += `Trigger this skill using: \`${skill.trigger.value}\`\n\n`;
    } else if (skill.trigger.type === 'keyword') {
      body += `This skill is triggered by keyword: **${skill.trigger.value}**\n\n`;
    } else if (skill.trigger.type === 'pattern') {
      body += `This skill is triggered by pattern: \`${skill.trigger.pattern}\`\n\n`;
    }

    // Parameters
    if (skill.parameters && skill.parameters.length > 0) {
      body += `## Parameters\n\n`;
      body += `| Name | Type | Required | Description | Default |\n`;
      body += `|------|------|----------|-------------|---------|\n`;
      skill.parameters.forEach((param) => {
        const required = param.required ? 'Yes' : 'No';
        const defaultVal =
          param.default !== undefined ? `\`${param.default}\`` : '-';
        body += `| ${param.name} | ${param.type} | ${required} | ${param.description} | ${defaultVal} |\n`;
      });
      body += `\n`;
    }

    // Examples
    if (skill.examples && skill.examples.length > 0) {
      body += `## Examples\n\n`;
      skill.examples.forEach((example, index) => {
        body += `### Example ${index + 1}\n\n`;
        if (example.description) {
          body += `${example.description}\n\n`;
        }
        body += `**Input:**\n\`\`\`\n${example.input}\n\`\`\`\n\n`;
        body += `**Output:**\n\`\`\`\n${example.output}\n\`\`\`\n\n`;
      });
    }

    // Integrations
    if (manifest.integrations) {
      body += `## Integrations\n\n`;

      if (manifest.integrations.mcp?.servers) {
        body += `### MCP Servers\n\n`;
        manifest.integrations.mcp.servers.forEach((server) => {
          body += `- ${server}\n`;
        });
        body += `\n`;
      }

      if (manifest.integrations.apis) {
        body += `### APIs\n\n`;
        manifest.integrations.apis.forEach((api) => {
          body += `- **${api.name}**: ${api.url}\n`;
        });
        body += `\n`;
      }
    }

    // Footer
    body += `---\n\n`;
    body += `*Generated by OSSA Generator v0.1.0*\n`;
    body += `*Specification: OSSA v${manifest.version}*\n`;

    return body;
  }

  /**
   * Generate all skills from manifest
   */
  generateAll(manifest: OSSAManifest): Map<string, string> {
    const skills = new Map<string, string>();

    if (!manifest.skills || manifest.skills.length === 0) {
      return skills;
    }

    manifest.skills.forEach((skill) => {
      const content = this.generate(manifest, skill.name);
      skills.set(skill.name, content);
    });

    return skills;
  }
}
