#!/usr/bin/env tsx
/**
 * Unified Config Generator
 * 
 * Generates GitLab agent configs, mesh configs, and infrastructure configs
 * from templates with DRY principles
 * 
 * Usage: npm run config:generate [--type gitlab-agent|mesh|infrastructure]
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import yaml from 'js-yaml';

interface ConfigTemplate {
  name: string;
  type: 'gitlab-agent' | 'mesh' | 'infrastructure';
  template: string;
  outputPath: string;
  variables: Record<string, string>;
}

class UnifiedConfigGenerator {
  private templates: Map<string, ConfigTemplate> = new Map();

  constructor() {
    this.registerTemplates();
  }

  private registerTemplates() {
    // GitLab Agent Config Template
    this.templates.set('gitlab-agent', {
      name: 'GitLab Kubernetes Agent Config',
      type: 'gitlab-agent',
      template: `# GitLab Kubernetes Agent Configuration for OSSA
# Generated by unified-config-generator

user_access:
  access_as:
    user: {}
  projects:
    - id: {{PROJECT_ID}}
  groups:
    - id: {{GROUP_ID}}

ci_access:
  projects:
    - id: {{PROJECT_ID}}
      access_as:
        impersonate:
          username: "gitlab:user:{{.user.username}}"
          groups:
            - "gitlab:group:{{.group.path}}"
            - "gitlab:project:{{.project.path_with_namespace}}"
  groups:
    - id: {{GROUP_ID}}
      access_as:
        impersonate:
          username: "gitlab:user:{{.user.username}}"
          groups:
            - "gitlab:group:{{.group.path}}"

remote_development:
  enabled: {{REMOTE_DEV_ENABLED}}
  max_per_user: {{MAX_REMOTE_DEV_PER_USER}}

observability:
  enabled: true
  metrics:
    enabled: true
    port: 9090
  logging:
    level: info
    format: json
  tracing:
    enabled: true
    provider: jaeger`,
      outputPath: '.gitlab/agents/config/gitlab-agents/config.yaml',
      variables: {
        PROJECT_ID: 'blueflyio/ossa/openstandardagents',
        GROUP_ID: 'blueflyio',
        REMOTE_DEV_ENABLED: 'false',
        MAX_REMOTE_DEV_PER_USER: '1'
      }
    });

    // Mesh Config Template
    this.templates.set('mesh', {
      name: 'Agent Mesh Configuration',
      type: 'mesh',
      template: `apiVersion: mesh.ossa.io/v1
kind: AgentMesh
metadata:
  name: {{MESH_NAME}}
  namespace: agent-mesh-system
  labels:
    environment: {{ENVIRONMENT}}
    deployment: kubernetes
    mesh-version: v1.0.0

spec:
  agents:
    - name: {{AGENT_NAME}}
      namespace: {{NAMESPACE}}
      endpoint: http://{{AGENT_NAME}}:8080
      healthCheck: http://{{AGENT_NAME}}:8080/health
      capabilities:
        - {{CAPABILITY_1}}
      dependencies: []

  protocols:
    - name: http
      port: 8080
      tls:
        enabled: {{TLS_ENABLED}}
    
  observability:
    metrics:
      enabled: true
      port: 9090
    tracing:
      enabled: true
      provider: jaeger`,
      outputPath: '.gitlab/agents/config/mesh-config.yaml',
      variables: {
        MESH_NAME: 'gitlab-k8s-agent-mesh',
        ENVIRONMENT: 'production',
        AGENT_NAME: 'security-scanner',
        NAMESPACE: 'security-system',
        CAPABILITY_1: 'vulnerability-scanning',
        TLS_ENABLED: 'true'
      }
    });

    // Infrastructure Config Template
    this.templates.set('infrastructure', {
      name: 'Infrastructure Configuration',
      type: 'infrastructure',
      template: `apiVersion: infrastructure.ossa.io/v1
kind: InfrastructureConfig
metadata:
  name: {{CONFIG_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    environment: {{ENVIRONMENT}}
    team: {{TEAM}}

spec:
  kubernetes:
    cluster:
      name: {{CLUSTER_NAME}}
      region: {{REGION}}
    
  monitoring:
    enabled: true
    prometheus:
      enabled: true
      retention: 30d
    grafana:
      enabled: true
      dashboards:
        - name: ossa-agents
          path: /grafana/dashboards/ossa-agents.json
    
  logging:
    enabled: true
    level: info
    retention: 7d
    
  security:
    enabled: true
    policies:
      - name: pod-security-standards
        level: restricted`,
      outputPath: '.gitlab/infrastructure/k8s/config.yaml',
      variables: {
        CONFIG_NAME: 'ossa-infrastructure',
        NAMESPACE: 'default',
        ENVIRONMENT: 'production',
        TEAM: 'platform',
        CLUSTER_NAME: 'ossa-cluster',
        REGION: 'us-east-1'
      }
    });
  }

  private replaceVariables(template: string, variables: Record<string, string>): string {
    let result = template;
    for (const [key, value] of Object.entries(variables)) {
      result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
    }
    return result;
  }

  async generate(type: string, options: Record<string, string> = {}): Promise<void> {
    const template = this.templates.get(type);
    if (!template) {
      console.error(`❌ Unknown config type: ${type}`);
      console.log(`Available types: ${Array.from(this.templates.keys()).join(', ')}`);
      process.exit(1);
    }

    console.log(`🚀 Generating ${template.name}...\n`);

    // Merge provided options with defaults
    const variables = { ...template.variables, ...options };

    // Replace variables in template
    const config = this.replaceVariables(template.template, variables);

    // Ensure output directory exists
    const outputDir = join(process.cwd(), template.outputPath.split('/').slice(0, -1).join('/'));
    mkdirSync(outputDir, { recursive: true });

    // Write config file
    const outputPath = join(process.cwd(), template.outputPath);
    writeFileSync(outputPath, config);

    console.log(`✅ Generated: ${template.outputPath}`);
    console.log(`   Variables used:`);
    Object.entries(variables).forEach(([key, value]) => {
      console.log(`     ${key}: ${value}`);
    });
  }

  async generateAll(options: Record<string, string> = {}): Promise<void> {
    console.log('🚀 Generating all configs...\n');
    
    for (const [type] of this.templates) {
      await this.generate(type, options);
      console.log('');
    }
    
    console.log('✅ All configs generated!');
  }
}

// CLI interface
const type = process.argv[2]?.replace('--type=', '') || 'all';
const generator = new UnifiedConfigGenerator();

// Parse additional options
const options: Record<string, string> = {};
process.argv.slice(3).forEach(arg => {
  const match = arg.match(/--(\w+)=(.+)/);
  if (match) {
    options[match[1].toUpperCase()] = match[2];
  }
});

if (type === 'all') {
  generator.generateAll(options).catch((error) => {
    console.error('❌ Error generating configs:', error);
    process.exit(1);
  });
} else {
  generator.generate(type, options).catch((error) => {
    console.error('❌ Error generating config:', error);
    process.exit(1);
  });
}

