/**
 * Agent Folder Structure Service
 *
 * Creates complete, standardized .agents folder structure following
 * OpenAPI-first, API-first, Zod, CRUD, SOLID, and DRY principles.
 *
 * SOLID: Single Responsibility - Only creates folder structure
 * DRY: Single source of truth (manifest), all code generated
 */

import * as fs from 'fs';
import * as path from 'path';
import type { OssaAgent } from '../../types/index.js';

export interface AgentFolderStructure {
  agentName: string;
  basePath: string;
  directories: string[];
  files: Array<{ path: string; content: string; description: string }>;
}

export class AgentsFolderService {
  /**
   * Generate complete agent folder structure
   */
  generateStructure(
    agentName: string,
    basePath: string = '.agents'
  ): AgentFolderStructure {
    const agentDir = path.join(basePath, agentName);

    const directories = [
      // Core structure
      agentDir,
      path.join(agentDir, 'prompts'),
      path.join(agentDir, 'prompts', 'examples'),
      path.join(agentDir, 'tools'),
      path.join(agentDir, 'tools', 'functions'),
      path.join(agentDir, 'tools', 'schemas'),
      path.join(agentDir, 'skills'),
      path.join(agentDir, 'config'),
      path.join(agentDir, 'api'),
      path.join(agentDir, 'src'),
      path.join(agentDir, 'src', 'adapters'),
      path.join(agentDir, 'src', 'runtime'),
      path.join(agentDir, 'src', 'mcp'),
      path.join(agentDir, 'tests'),
      path.join(agentDir, 'tests', 'unit'),
      path.join(agentDir, 'tests', 'integration'),
      path.join(agentDir, 'tests', 'fixtures'),
      path.join(agentDir, 'docs'),
      path.join(agentDir, 'docker'),
      path.join(agentDir, 'k8s'),
    ];

    const files: Array<{ path: string; content: string; description: string }> =
      [
        // Core manifest (will be created by wizard/scaffold)
        {
          path: path.join(agentDir, 'manifest.ossa.yaml'),
          content:
            '# OSSA Manifest - Single Source of Truth\n# Generated by ossa wizard\n',
          description: 'OSSA manifest (single source of truth)',
        },

        // OpenAPI spec placeholder (will be generated)
        {
          path: path.join(agentDir, 'openapi.yaml'),
          content:
            '# OpenAPI 3.1 Specification\n# Generated from manifest.ossa.yaml\n# Use: ossa generate openapi\n',
          description: 'OpenAPI spec (generated from manifest)',
        },

        // Zod schemas placeholder (will be generated)
        {
          path: path.join(agentDir, 'zod-schemas.ts'),
          content:
            '// Zod schemas generated from OpenAPI\n// Use: ossa generate zod\n',
          description: 'Zod schemas (generated from OpenAPI)',
        },

        // API client placeholder (will be generated)
        {
          path: path.join(agentDir, 'api-client.ts'),
          content:
            '// Type-safe API client generated from OpenAPI\n// Use: ossa generate client\n',
          description: 'API client (generated from OpenAPI)',
        },

        // Prompt templates
        {
          path: path.join(agentDir, 'prompts', 'system.txt'),
          content: "# System Prompt\n# Define the agent's role and behavior\n",
          description: 'System prompt template',
        },
        {
          path: path.join(agentDir, 'prompts', 'user-template.jinja2'),
          content:
            '# User Prompt Template\n# Jinja2 template for user prompts\n',
          description: 'User prompt template (Jinja2)',
        },

        // Tools configuration
        {
          path: path.join(agentDir, 'tools', 'tools.yaml'),
          content: '# Tool Registry\n# MCP-first tool definitions\n',
          description: 'Tool registry (MCP-first)',
        },
        {
          path: path.join(agentDir, 'tools', 'mcp-servers.yaml'),
          content:
            '# MCP Server Configurations\n# Model Context Protocol servers\n',
          description: 'MCP server configurations',
        },

        // Config files
        {
          path: path.join(agentDir, 'config', 'development.yaml'),
          content: '# Development Configuration\n',
          description: 'Development config',
        },
        {
          path: path.join(agentDir, 'config', 'staging.yaml'),
          content: '# Staging Configuration\n',
          description: 'Staging config',
        },
        {
          path: path.join(agentDir, 'config', 'production.yaml'),
          content: '# Production Configuration\n',
          description: 'Production config',
        },
        {
          path: path.join(agentDir, 'config', 'local.yaml'),
          content: '# Local Configuration\n',
          description: 'Local config',
        },

        // API structure (CRUD)
        {
          path: path.join(agentDir, 'api', 'routes.ts'),
          content: `// REST API Routes\n// Generated from OpenAPI spec\nimport { Router } from 'express';\n\nconst router = Router();\n\n// Routes will be generated from OpenAPI spec\n\nexport default router;\n`,
          description: 'API routes (generated from OpenAPI)',
        },
        {
          path: path.join(agentDir, 'api', 'controllers.ts'),
          content: `// API Controllers (SOLID)\n// Single Responsibility: HTTP handling only\n\nimport type { Request, Response } from 'express';\n\nexport class AgentController {\n  // Controllers will be generated\n}\n`,
          description: 'API controllers (SOLID)',
        },
        {
          path: path.join(agentDir, 'api', 'services.ts'),
          content: `// Business Logic Services (SOLID)\n// Single Responsibility: Business logic only\n\nexport class AgentService {\n  // Services will be generated\n}\n`,
          description: 'Business logic services (SOLID)',
        },
        {
          path: path.join(agentDir, 'api', 'repositories.ts'),
          content: `// Data Access Repositories (SOLID)\n// Single Responsibility: Data access only\n\nexport interface IAgentRepository {\n  // Repository interface will be generated\n}\n`,
          description: 'Data access repositories (SOLID)',
        },
        {
          path: path.join(agentDir, 'api', 'middleware.ts'),
          content: `// API Middleware\n// Validation, auth, error handling\n\nimport { z } from 'zod';\n\n// Middleware will be generated\n`,
          description: 'API middleware (validation, auth)',
        },

        // Source code structure
        {
          path: path.join(agentDir, 'src', 'index.ts'),
          content: `// Agent Entry Point\n// Platform-agnostic runtime\n\nimport { AgentRuntime } from './runtime/agent-runtime';\n\nexport { AgentRuntime };\n`,
          description: 'Agent entry point',
        },
        {
          path: path.join(agentDir, 'src', 'adapters', 'base.adapter.ts'),
          content: `// Base LLM Adapter Interface (SOLID)\n// All adapters must implement this interface\n\nexport interface BaseAdapter {\n  initialize(manifest: OssaManifest): void;\n  chat(message: string, options?: RunOptions): Promise<string>;\n  chatStream(message: string, options?: RunOptions): AsyncGenerator<string>;\n  registerToolHandler(name: string, handler: ToolHandler): void;\n  getConversationHistory(): Message[];\n  clearHistory(): void;\n  getAgentInfo(): AgentInfo;\n}\n`,
          description: 'Base adapter interface (SOLID)',
        },
        {
          path: path.join(agentDir, 'src', 'runtime', 'agent-runtime.ts'),
          content: `// Agent Runtime\n// Platform-agnostic runtime binding\n\nimport { loadManifest } from '@ossa/sdk';\nimport { getAdapter } from '../adapters';\n\nexport class AgentRuntime {\n  private adapter: BaseAdapter;\n\n  async initialize(manifestPath: string) {\n    const manifest = await loadManifest(manifestPath);\n    const provider = manifest.spec.llm?.provider || 'anthropic';\n    this.adapter = getAdapter(provider);\n    this.adapter.initialize(manifest);\n  }\n\n  async chat(message: string) {\n    return this.adapter.chat(message);\n  }\n}\n`,
          description: 'Agent runtime (platform-agnostic)',
        },
        {
          path: path.join(agentDir, 'src', 'mcp', 'mcp-client.ts'),
          content: `// MCP Client\n// Model Context Protocol integration\n\nimport { Client } from '@modelcontextprotocol/sdk/client';\n\nexport class MCPClient {\n  // MCP client implementation\n}\n`,
          description: 'MCP client integration',
        },

        // Test structure
        {
          path: path.join(agentDir, 'tests', 'unit', 'adapters.test.ts'),
          content: `// Adapter Unit Tests\nimport { describe, it, expect } from 'vitest';\n\n// Tests will be generated\n`,
          description: 'Adapter unit tests',
        },
        {
          path: path.join(agentDir, 'tests', 'unit', 'api.test.ts'),
          content: `// API Unit Tests\nimport { describe, it, expect } from 'vitest';\n\n// Tests will be generated\n`,
          description: 'API unit tests',
        },
        {
          path: path.join(agentDir, 'tests', 'integration', 'agent.test.ts'),
          content: `// Agent Integration Tests\nimport { describe, it, expect } from 'vitest';\n\n// Tests will be generated\n`,
          description: 'Agent integration tests',
        },

        // Documentation
        {
          path: path.join(agentDir, 'docs', 'architecture.md'),
          content: `# Architecture Documentation\n\n## Overview\n\nThis agent follows OpenAPI-first, API-first, Zod, CRUD, SOLID, and DRY principles.\n\n## Structure\n\n- \`manifest.ossa.yaml\` - Single source of truth\n- \`openapi.yaml\` - Generated from manifest\n- \`zod-schemas.ts\` - Generated from OpenAPI\n- \`api-client.ts\` - Generated from OpenAPI\n`,
          description: 'Architecture documentation',
        },
        {
          path: path.join(agentDir, 'docs', 'api.md'),
          content: `# API Documentation\n\nGenerated from OpenAPI spec.\n\nUse: \`ossa docs generate\`\n`,
          description: 'API documentation (from OpenAPI)',
        },

        // Docker
        {
          path: path.join(agentDir, 'docker', 'Dockerfile'),
          content: `# Dockerfile\n# Multi-stage build for production\n\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY --from=builder /app/node_modules ./node_modules\nCMD ["node", "dist/index.js"]\n`,
          description: 'Dockerfile',
        },

        // Kubernetes
        {
          path: path.join(agentDir, 'k8s', 'deployment.yaml'),
          content: `# Kubernetes Deployment\n# Generated from manifest\n\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ${agentName}\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: ${agentName}\n  template:\n    metadata:\n      labels:\n        app: ${agentName}\n    spec:\n      containers:\n      - name: ${agentName}\n        image: ${agentName}:latest\n`,
          description: 'Kubernetes deployment',
        },

        // Root files
        {
          path: path.join(agentDir, 'package.json'),
          content: JSON.stringify(
            {
              name: agentName,
              version: '1.0.0',
              type: 'module',
              main: 'dist/index.js',
              scripts: {
                build: 'tsc',
                test: 'vitest',
                validate: 'ossa validate manifest.ossa.yaml',
                'generate:openapi': 'ossa generate openapi manifest.ossa.yaml',
                'generate:zod': 'ossa generate zod openapi.yaml',
                'generate:client': 'ossa generate client openapi.yaml',
              },
              dependencies: {
                '@ossa/sdk': '^0.3.5',
                zod: '^3.22.0',
              },
              devDependencies: {
                '@types/node': '^20.0.0',
                typescript: '^5.0.0',
                vitest: '^1.0.0',
              },
            },
            null,
            2
          ),
          description: 'package.json',
        },
        {
          path: path.join(agentDir, 'tsconfig.json'),
          content: JSON.stringify(
            {
              compilerOptions: {
                target: 'ES2022',
                module: 'ESNext',
                lib: ['ES2022'],
                moduleResolution: 'node',
                outDir: './dist',
                rootDir: './src',
                strict: true,
                esModuleInterop: true,
                skipLibCheck: true,
                forceConsistentCasingInFileNames: true,
              },
              include: ['src/**/*'],
              exclude: ['node_modules', 'dist', 'tests'],
            },
            null,
            2
          ),
          description: 'TypeScript config',
        },
        {
          path: path.join(agentDir, 'AGENTS.md'),
          content: `# AGENTS.md\n\n## Dev environment tips\n\n- Use Node.js 20+\n- Run \`npm install\` to install dependencies\n- Run \`npm run build\` to build\n\n## Testing instructions\n\n- Run \`npm test\` for unit tests\n- Run \`npm run test:integration\` for integration tests\n\n## PR instructions\n\n- Use conventional commits\n- Run \`npm run validate\` before committing\n`,
          description: 'AGENTS.md (AAIF standard)',
        },
        {
          path: path.join(agentDir, 'README.md'),
          content: `# ${agentName}\n\nOSSA-compliant agent following OpenAPI-first, API-first, Zod, CRUD, SOLID, and DRY principles.\n\n## Structure\n\n- \`manifest.ossa.yaml\` - Single source of truth\n- \`openapi.yaml\` - Generated from manifest\n- \`zod-schemas.ts\` - Generated from OpenAPI\n- \`api-client.ts\` - Generated from OpenAPI\n\n## Usage\n\n\`\`\`bash\n# Validate manifest\nossa validate manifest.ossa.yaml\n\n# Generate OpenAPI\nossa generate openapi manifest.ossa.yaml\n\n# Generate Zod schemas\nossa generate zod openapi.yaml\n\n# Generate API client\nossa generate client openapi.yaml\n\`\`\`\n`,
          description: 'README.md',
        },
      ];

    return {
      agentName,
      basePath,
      directories,
      files,
    };
  }

  /**
   * Create folder structure on filesystem
   */
  createStructure(
    structure: AgentFolderStructure,
    overwrite: boolean = false
  ): void {
    // Create directories
    for (const dir of structure.directories) {
      if (fs.existsSync(dir) && !overwrite) {
        continue;
      }
      fs.mkdirSync(dir, { recursive: true });
    }

    // Create files
    for (const file of structure.files) {
      if (fs.existsSync(file.path) && !overwrite) {
        continue;
      }
      fs.writeFileSync(file.path, file.content, 'utf-8');
    }
  }

  /**
   * Validate folder structure
   */
  validateStructure(agentDir: string): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const requiredDirs = [
      'prompts',
      'tools',
      'config',
      'api',
      'src',
      'tests',
      'docs',
    ];
    const requiredFiles = [
      'manifest.ossa.yaml',
      'package.json',
      'tsconfig.json',
      'README.md',
    ];

    for (const dir of requiredDirs) {
      const dirPath = path.join(agentDir, dir);
      if (!fs.existsSync(dirPath)) {
        errors.push(`Missing directory: ${dir}`);
      }
    }

    for (const file of requiredFiles) {
      const filePath = path.join(agentDir, file);
      if (!fs.existsSync(filePath)) {
        errors.push(`Missing file: ${file}`);
      }
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }
}
