// Dynamic version loading from versions.json
// This file loads version data generated by scripts/fetch-versions.js

import versionsData from './versions.json';

export interface VersionInfo {
  version: string;
  tag: string;
  apiVersion: string;
  type: 'stable' | 'dev' | 'prerelease' | 'local';
  published: boolean;
  available: boolean;
  schemaPath?: string;
}

export interface VersionsData {
  stable: string;
  latest: string;
  dev: string;
  all: VersionInfo[];
  fallbackVersion: string;
}

export const VERSIONS_DATA: VersionsData = versionsData;

export const STABLE_VERSION = VERSIONS_DATA.stable;
export const LATEST_VERSION = VERSIONS_DATA.latest;
export const DEV_VERSION = VERSIONS_DATA.dev;
export const FALLBACK_VERSION = VERSIONS_DATA.fallbackVersion;

export const ALL_VERSIONS: VersionInfo[] = VERSIONS_DATA.all;
export const STABLE_VERSIONS: VersionInfo[] = ALL_VERSIONS.filter(v => v.type === 'stable');
export const DEV_VERSIONS: VersionInfo[] = ALL_VERSIONS.filter(v => v.type === 'dev' || v.type === 'prerelease');

export const STABLE_VERSION_TAG = `v${STABLE_VERSION}`;
export const DEV_VERSION_TAG = DEV_VERSION ? `v${DEV_VERSION}` : undefined;
export const OSSA_API_VERSION = `ossa/v${STABLE_VERSION}`;

export function getVersionInfo(version: string): VersionInfo | undefined {
  return ALL_VERSIONS.find(v => v.version === version || v.tag === `v${version}`);
}

export function getSchemaPath(version: string): string | undefined {
  const info = getVersionInfo(version);
  if (info?.schemaPath) {
    return info.schemaPath;
  }
  // Fallback: construct path from version
  return `/schemas/ossa-${version}.schema.json`;
}
