# Bluefly Agent Platform Services Overview

This document provides a concise summary of the deployed applications and services on the Bluefly Agents platform. The services are categorized by their primary function within the architecture.

## Infrastructure & Networking

**nas** (`nas.blueflyagents.com`)
This is the Synology NAS management interface handling centralized storage. It hosts the bare git repositories and foundational network drives for the platform. It provides the core file system infrastructure for local development and backups.

**storage** (`storage.blueflyagents.com`)
This service provides an S3-compatible object storage layer, likely powered by MinIO. It is used to store large artifacts, agent outputs, and persistent application data. It provides a scalable way for agents to read and write unstructured files.

**router** (`router.blueflyagents.com`)
This operates as the internal API gateway and reverse proxy for the platform. It routes incoming requests to the appropriate microservices securely. It likely handles edge and internal load balancing for the platform's various endpoints.

**infra** (`infra.blueflyagents.com`)
This service is a centralized dashboard for managing underlying platform infrastructure. It provides visibility into resource allocation, server health, and virtualized components. It helps administrators ensure the physical and virtual base layer is operating smoothly.

**api** (`api.blueflyagents.com`)
This acts as the unified external API endpoint for the Bluefly platform. It exposes platform capabilities securely to external consumers or custom frontend applications. It consolidates interactions so clients don't need to know the internal microservice topology.

**mesh** (`mesh.blueflyagents.com`)
This service acts as the central communication hub and gateway for the Agent Mesh. It dynamically routes requests and messages between different agents and services. It forms the backbone of the agentic network's internal connectivity.

## Agent Platform Core

**agents** (`agents.blueflyagents.com`)
This is the core execution platform for individual AI agents. It handles the lifecycle management, instantiation, and basic routing for agent workloads. It acts as the foundational runtime environment for custom agent logic.

**orchestrator** (`orchestrator.blueflyagents.com`)
This service handles high-level task delegation and multi-agent coordination. It breaks down complex user requests and distributes sub-tasks to specialized worker agents. It ensures workflows complete successfully by managing interdependencies.

**kagent** (`kagent.blueflyagents.com`)
This serves as the backend for the specialized Knowledge Agent. It is responsible for processing, structuring, and retrieving knowledge across the platform. It likely interfaces closely with vector databases and graph systems to answer complex queries.

**kagent-ui** (`kagent-ui.blueflyagents.com`)
This provides the user interface for interacting directly with the Knowledge Agent. Users can visually query the knowledge base, manage document ingestions, and adjust retrieval parameters. It makes the underlying RAG capabilities accessible to operators.

**mcp** (`mcp.blueflyagents.com`)
This operates the Model Context Protocol (MCP) server for the network. It standardizes how local resources, databases, and APIs are securely exposed to LLMs. It ensures agents have a unified way to access external context quickly.

**mcpdash** (`mcpdash.blueflyagents.com`)
This is the management dashboard for the Model Context Protocol ecosystem. It allows administrators to view connected MCP servers, monitor resource usage, and configure access permissions. It provides operational visibility into context provisioning.

**ecma-agent** (`ecma-agent.blueflyagents.com`)
This is a specialized execution agent designed specifically for JavaScript/ECMAScript environments. It provides a sandboxed runtime for dynamically executing code generated by LLMs. It allows the platform to securely perform complex data manipulation and API calls on the fly.

## Agentic Communications

**a2a-stream** (`a2a-stream.blueflyagents.com`)
This service facilitates real-time streaming communication between active agents. It operates as an event bus or pub/sub system to broadcast messages across the mesh. It enables agents to collaborate synchronously on complex ongoing tasks.

**a2a-collector** (`a2a-collector.blueflyagents.com`)
This acts as the telemetry collector for Agent-to-Agent (A2A) interactions. It ingests logs, metrics, and message payloads from communications within the agent mesh. It provides the raw data needed to audit and optimize multi-agent workflows.

## Databases & Knowledge Systems

**brain** (`brain.blueflyagents.com`)
This hosts the Qdrant vector database (or similar) underlying the platform's semantic memory. It stores high-dimensional embeddings of documents and conversations for fast similarity search. It is the primary engine fueling the retrieval-augmented generation (RAG) capabilities.

**dragonfly** (`dragonfly.blueflyagents.com`)
This serves as a high-performance, in-memory datastore acting as a Redis alternative. It is used for rapid caching, session management, and short-term message brokering. It significantly speeds up platform responsiveness for ephemeral data.

**obsidian** (`obsidian.blueflyagents.com`)
This provides the CouchDB backend designed to sync Obsidian markdown vaults. It enables real-time synchronization of human and agent-generated notes across devices. It forms a crucial part of the platform's unstructured personal knowledge management.

**zotero** (`zotero.blueflyagents.com`)
This is a self-hosted synchronization server for the Zotero reference management system. It securely stores academic papers, web clippings, and bibliographies for agent or human research. It acts as a specialized repository for structured reference material.

**gkg** (`gkg.blueflyagents.com`)
This represents the Global Knowledge Graph service. It stores interconnected relational facts, entities, and ontologies derived from ingested documents. It allows agents to perform complex, multi-hop reasoning over structured data.

## Workflow & Visual Builders

**n8n** (`n8n.blueflyagents.com`)
This is an extendable workflow automation tool for connecting APIs and services. It provides a visual, node-based interface for building complex integrations without code. It is heavily utilized for standardizing deterministic business processes.

**flowise** (`flowise.blueflyagents.com`)
This is an open-source, low-code UI builder customized for LLM applications. It allows users to visually compose RAG pipelines, agent chains, and prompt workflows. It serves as a rapid prototyping tool for new cognitive capabilities.

**langflow** (`langflow.blueflyagents.com`)
This is another visual framework for building multi-agent and LLM-powered applications. It provides drag-and-drop components for LangChain and allied ecosystems. It makes complex agent architectures easier to design, test, and deploy visually.

**workflow** (`workflow.blueflyagents.com`)
This is an internal workflow execution engine specific to the Bluefly platform. It manages stateful, multi-step processes that may span days or involve human-in-the-loop approvals. It provides durability and retry logic for long-running platform operations.

## User Interfaces & Ideation

**chat** (`chat.blueflyagents.com`)
This serves as the primary conversational interface for interacting with the LLMs. It provides a user-friendly chat application (like Open WebUI) to test and communicate with various models. It is the main entry point for conversational agent interactions.

**studio** (`studio.blueflyagents.com`)
This is a dedicated developer environment for building and fine-tuning individual agents. It provides interfaces for prompt engineering, tool assignment, and behavior testing. It streamlines the creation process before agents are published to the network.

**ossa-ui** (`ossa-ui.blueflyagents.com`)
This is a specialized user interface likely dedicated to Open Source Software Analytics or Security. It provides a dashboard to evaluate external packages and dependencies for the platform. It gives developers insights into the health and safety of their software supply chain.

## Ecosystem & Marketplace

**npm** (`npm.blueflyagents.com`)
This hosts a Verdaccio private NPM registry on the NAS. It stores proprietary internal packages and custom agent tools not meant for public release. It also acts as a caching proxy for the public NPM registry to speed up local builds.

**marketplace** (`marketplace.blueflyagents.com`)
This operates as an internal catalog for teams to share and discover pre-built agent templates. It allows users to quickly deploy proven agent configurations for specific use cases. It accelerates adoption by standardizing common agent patterns across the organization.

**plugins** (`plugins.blueflyagents.com`)
This is the central registry and distribution server for modular agent plugins. It hosts discoverable extensions that instantly add new integrations to the platform. It allows the ecosystem to grow seamlessly without modifying core agent code.

**skills** (`skills.blueflyagents.com`)
This manages a repository of discrete logic functions or "skills" that agents can execute. By decoupling tools from the agents themselves, this service ensures capabilities are reusable. Agents can query this directory to dynamically load new toolsets on demand.

**intel** (`intel.blueflyagents.com`)
This functions as an intelligence gathering and aggregation system. It consolidates internal metrics, external data feeds, and threat intelligence into a unified view. It provides high-level situational awareness for advanced analytical agents.

## Observability & Governance

**grafana** (`grafana.blueflyagents.com`)
This serves as the primary observability platform via Grafana dashboards. It visualizes infrastructure metrics, logs, and application performance data centrally. It is essential for monitoring the hardware and software health of the entire environment.

**tracer** (`tracer.blueflyagents.com`)
This captures and visualizes distributed execution traces for LLM calls and agent chains. Using tools like Langfuse or Jaeger, it monitors token usage, latency, and prompt effectiveness. It is critical for debugging complex reasoning chains and optimizing costs.

**adash** (`adash.blueflyagents.com`)
This is the general Agent Dashboard providing a high-level operational overview. It tracks the real-time status, health, and activity levels of all active agents on the mesh. It is the primary screen for operators managing the agent fleet.

**content-guardian** (`content-guardian.blueflyagents.com`)
This is a security and moderation service sitting between the LLMs and users. It analyzes inputs and outputs to apply safety filters and prevent data exfiltration. It ensures all agent interactions adhere to established compliance rules.

**compliance** (`compliance.blueflyagents.com`)
This handles overarching policy enforcement and audit logging for the network. It records immutable logs of agent decisions to satisfy regulatory or internal governance requirements. It guarantees transparency in automated decision-making.

**happy** (`happy.blueflyagents.com`)
This is a streamlined health-check and system uptime monitor. It frequently pings vital services across the platform to ensure they return standard OK responses. It provides immediate alerts if critical path services go down.

## DevOps & Developer Tools

**dockge** (`dockge.blueflyagents.com`)
This provides a reactive, self-hosted frontend for managing docker-compose stacks. Hosted on the NAS, it simplifies the deployment and updating of containerized applications. It acts as an accessible alternative to command-line Docker management.

**code** (`code.blueflyagents.com`)
This hosts a web-based VS Code environment directly on the platform infrastructure. It provides developers with a persistent, remote coding space pre-configured with the platform's networks. It allows for seamless editing and debugging directly against internal services.

**devops** (`devops.blueflyagents.com`)
This is the central continuous integration and deployment (CI/CD) service. It automates the building of agent images, running tests, and managing release pipelines. It ensures that infrastructure updates are pushed reliably and consistently.

**dev-adash** (`dev-adash.blueflyagents.com`)
This is the development and staging instance of the Agent Dashboard. It allows developers to test UI regressions and new features safely before pushing to production.

**dev-mdash** (`dev-mdash.blueflyagents.com`)
This is a designated development instance, likely for the Mesh or Model dashboards. It serves as a sandbox to test new monitoring and routing visualizations in isolation.

**dev-fleet** (`dev-fleet.blueflyagents.com`)
This is a development testing ground for the Fleet Management system. It is used to test orchestration logic against simulated or staging agents without impacting the live mesh.
