"""
Agent Folder Structure Service (Python)
Creates complete, standardized .agents folder structure following
OpenAPI-first, API-first, Pydantic, CRUD, SOLID, and DRY principles.

SOLID: Single Responsibility - Only creates folder structure
DRY: Single source of truth (manifest), all code generated
"""

import os
import json
from pathlib import Path
from typing import List, Dict, Optional
from dataclasses import dataclass


@dataclass
class FileDefinition:
    """File definition with path, content, and description"""
    path: str
    content: str
    description: str


@dataclass
class AgentFolderStructure:
    """Complete agent folder structure definition"""
    agent_name: str
    base_path: str
    directories: List[str]
    files: List[FileDefinition]


class AgentsFolderService:
    """Service for generating agent folder structures"""

    def generate_structure(
        self, agent_name: str, base_path: str = ".agents"
    ) -> AgentFolderStructure:
        """Generate complete agent folder structure"""
        agent_dir = Path(base_path) / agent_name

        directories = [
            # Core structure
            str(agent_dir),
            str(agent_dir / "prompts"),
            str(agent_dir / "prompts" / "examples"),
            str(agent_dir / "tools"),
            str(agent_dir / "tools" / "functions"),
            str(agent_dir / "tools" / "schemas"),
            str(agent_dir / "skills"),
            str(agent_dir / "config"),
            str(agent_dir / "api"),
            str(agent_dir / "src"),
            str(agent_dir / "src" / "adapters"),
            str(agent_dir / "src" / "runtime"),
            str(agent_dir / "src" / "mcp"),
            str(agent_dir / "tests"),
            str(agent_dir / "tests" / "unit"),
            str(agent_dir / "tests" / "integration"),
            str(agent_dir / "tests" / "fixtures"),
            str(agent_dir / "docs"),
            str(agent_dir / "docker"),
            str(agent_dir / "k8s"),
        ]

        files: List[FileDefinition] = [
            # Core manifest (will be created by wizard/scaffold)
            FileDefinition(
                path=str(agent_dir / "manifest.ossa.yaml"),
                content="# OSSA Manifest - Single Source of Truth\n# Generated by ossa wizard\n",
                description="OSSA manifest (single source of truth)",
            ),
            # OpenAPI spec placeholder (will be generated)
            FileDefinition(
                path=str(agent_dir / "openapi.yaml"),
                content="# OpenAPI 3.1 Specification\n# Generated from manifest.ossa.yaml\n# Use: ossa generate openapi\n",
                description="OpenAPI spec (generated from manifest)",
            ),
            # Pydantic models placeholder (will be generated)
            FileDefinition(
                path=str(agent_dir / "pydantic_models.py"),
                content="# Pydantic models generated from OpenAPI\n# Use: ossa generate pydantic\n",
                description="Pydantic models (generated from OpenAPI)",
            ),
            # API client placeholder (will be generated)
            FileDefinition(
                path=str(agent_dir / "client.py"),
                content="# Type-safe API client generated from OpenAPI\n# Use: ossa generate client\n",
                description="API client (generated from OpenAPI)",
            ),
            # Prompt templates
            FileDefinition(
                path=str(agent_dir / "prompts" / "system.txt"),
                content="# System Prompt\n# Define the agent's role and behavior\n",
                description="System prompt template",
            ),
            FileDefinition(
                path=str(agent_dir / "prompts" / "user_template.jinja2"),
                content="# User Prompt Template\n# Jinja2 template for user prompts\n",
                description="User prompt template (Jinja2)",
            ),
            # Tools configuration
            FileDefinition(
                path=str(agent_dir / "tools" / "tools.yaml"),
                content="# Tool Registry\n# MCP-first tool definitions\n",
                description="Tool registry (MCP-first)",
            ),
            FileDefinition(
                path=str(agent_dir / "tools" / "mcp_servers.yaml"),
                content="# MCP Server Configurations\n# Model Context Protocol servers\n",
                description="MCP server configurations",
            ),
            # Config files
            FileDefinition(
                path=str(agent_dir / "config" / "development.yaml"),
                content="# Development Configuration\n",
                description="Development config",
            ),
            FileDefinition(
                path=str(agent_dir / "config" / "staging.yaml"),
                content="# Staging Configuration\n",
                description="Staging config",
            ),
            FileDefinition(
                path=str(agent_dir / "config" / "production.yaml"),
                content="# Production Configuration\n",
                description="Production config",
            ),
            FileDefinition(
                path=str(agent_dir / "config" / "local.yaml"),
                content="# Local Configuration\n",
                description="Local config",
            ),
            # API structure (CRUD)
            FileDefinition(
                path=str(agent_dir / "api" / "routes.py"),
                content='"""REST API Routes\nGenerated from OpenAPI spec"""\nfrom fastapi import APIRouter\n\nrouter = APIRouter()\n\n# Routes will be generated from OpenAPI spec\n',
                description="API routes (generated from OpenAPI)",
            ),
            FileDefinition(
                path=str(agent_dir / "api" / "controllers.py"),
                content='"""API Controllers (SOLID)\nSingle Responsibility: HTTP handling only"""\nfrom fastapi import Request, Response\n\n# Controllers will be generated\n',
                description="API controllers (SOLID)",
            ),
            FileDefinition(
                path=str(agent_dir / "api" / "services.py"),
                content='"""Business Logic Services (SOLID)\nSingle Responsibility: Business logic only"""\n\n# Services will be generated\n',
                description="Business logic services (SOLID)",
            ),
            FileDefinition(
                path=str(agent_dir / "api" / "repositories.py"),
                content='"""Data Access Repositories (SOLID)\nSingle Responsibility: Data access only"""\nfrom abc import ABC, abstractmethod\n\nclass IAgentRepository(ABC):\n    """Repository interface will be generated"""\n    pass\n',
                description="Data access repositories (SOLID)",
            ),
            FileDefinition(
                path=str(agent_dir / "api" / "middleware.py"),
                content='"""API Middleware\nValidation, auth, error handling"""\nfrom fastapi import Request\nfrom pydantic import BaseModel\n\n# Middleware will be generated\n',
                description="API middleware (validation, auth)",
            ),
            # Source code structure
            FileDefinition(
                path=str(agent_dir / "src" / "__init__.py"),
                content='"""Agent Entry Point\nPlatform-agnostic runtime"""\nfrom .runtime.agent_runtime import AgentRuntime\n\n__all__ = ["AgentRuntime"]\n',
                description="Agent entry point",
            ),
            FileDefinition(
                path=str(agent_dir / "src" / "adapters" / "__init__.py"),
                content='"""LLM Adapters"""\nfrom .base import BaseAdapter\n\n__all__ = ["BaseAdapter"]\n',
                description="Adapters package",
            ),
            FileDefinition(
                path=str(agent_dir / "src" / "adapters" / "base.py"),
                content='"""Base LLM Adapter Interface (SOLID)\nAll adapters must implement this interface"""\nfrom abc import ABC, abstractmethod\nfrom typing import AsyncIterator, Optional\n\nclass BaseAdapter(ABC):\n    """Base interface for all LLM adapters"""\n    \n    @abstractmethod\n    async def initialize(self, manifest: dict) -> None:\n        """Initialize adapter with manifest"""\n        pass\n    \n    @abstractmethod\n    async def chat(self, message: str, **kwargs) -> str:\n        """Send message and get response"""\n        pass\n    \n    @abstractmethod\n    async def chat_stream(self, message: str, **kwargs) -> AsyncIterator[str]:\n        """Stream response"""\n        pass\n    \n    @abstractmethod\n    def register_tool_handler(self, name: str, handler: callable) -> None:\n        """Register tool handler"""\n        pass\n',
                description="Base adapter interface (SOLID)",
            ),
            FileDefinition(
                path=str(agent_dir / "src" / "runtime" / "__init__.py"),
                content='"""Agent Runtime"""\nfrom .agent_runtime import AgentRuntime\n\n__all__ = ["AgentRuntime"]\n',
                description="Runtime package",
            ),
            FileDefinition(
                path=str(agent_dir / "src" / "runtime" / "agent_runtime.py"),
                content='"""Agent Runtime\nPlatform-agnostic runtime binding"""\nfrom ossa import load_manifest\nfrom ..adapters import get_adapter\n\nclass AgentRuntime:\n    """Platform-agnostic agent runtime"""\n    \n    def __init__(self, manifest_path: str):\n        self.manifest = load_manifest(manifest_path)\n        provider = self.manifest.spec.llm.provider if self.manifest.spec.llm else "anthropic"\n        self.adapter = get_adapter(provider)\n        self.adapter.initialize(self.manifest)\n    \n    async def chat(self, message: str) -> str:\n        """Chat with agent"""\n        return await self.adapter.chat(message)\n',
                description="Agent runtime (platform-agnostic)",
            ),
            FileDefinition(
                path=str(agent_dir / "src" / "mcp" / "__init__.py"),
                content='"""MCP Client\nModel Context Protocol integration"""\nfrom .mcp_client import MCPClient\n\n__all__ = ["MCPClient"]\n',
                description="MCP package",
            ),
            FileDefinition(
                path=str(agent_dir / "src" / "mcp" / "mcp_client.py"),
                content='"""MCP Client\nModel Context Protocol integration"""\n\nclass MCPClient:\n    """MCP client implementation"""\n    pass\n',
                description="MCP client integration",
            ),
            # Test structure
            FileDefinition(
                path=str(agent_dir / "tests" / "__init__.py"),
                content="",
                description="Tests package",
            ),
            FileDefinition(
                path=str(agent_dir / "tests" / "unit" / "__init__.py"),
                content="",
                description="Unit tests package",
            ),
            FileDefinition(
                path=str(agent_dir / "tests" / "unit" / "test_adapters.py"),
                content='"""Adapter Unit Tests"""\nimport pytest\n\n# Tests will be generated\n',
                description="Adapter unit tests",
            ),
            FileDefinition(
                path=str(agent_dir / "tests" / "unit" / "test_api.py"),
                content='"""API Unit Tests"""\nimport pytest\n\n# Tests will be generated\n',
                description="API unit tests",
            ),
            FileDefinition(
                path=str(agent_dir / "tests" / "integration" / "__init__.py"),
                content="",
                description="Integration tests package",
            ),
            FileDefinition(
                path=str(agent_dir / "tests" / "integration" / "test_agent.py"),
                content='"""Agent Integration Tests"""\nimport pytest\n\n# Tests will be generated\n',
                description="Agent integration tests",
            ),
            # Documentation
            FileDefinition(
                path=str(agent_dir / "docs" / "architecture.md"),
                content="# Architecture Documentation\n\n## Overview\n\nThis agent follows OpenAPI-first, API-first, Pydantic, CRUD, SOLID, and DRY principles.\n\n## Structure\n\n- `manifest.ossa.yaml` - Single source of truth\n- `openapi.yaml` - Generated from manifest\n- `pydantic_models.py` - Generated from OpenAPI\n- `client.py` - Generated from OpenAPI\n",
                description="Architecture documentation",
            ),
            FileDefinition(
                path=str(agent_dir / "docs" / "api.md"),
                content="# API Documentation\n\nGenerated from OpenAPI spec.\n\nUse: `ossa docs generate`\n",
                description="API documentation (from OpenAPI)",
            ),
            # Docker
            FileDefinition(
                path=str(agent_dir / "docker" / "Dockerfile"),
                content="# Dockerfile\n# Multi-stage build for production\n\nFROM python:3.11-slim AS builder\nWORKDIR /app\nCOPY requirements*.txt ./\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\n\nFROM python:3.11-slim\nWORKDIR /app\nCOPY --from=builder /app /app\nCMD [\"python\", \"-m\", \"src\"]\n",
                description="Dockerfile",
            ),
            # Kubernetes
            FileDefinition(
                path=str(agent_dir / "k8s" / "deployment.yaml"),
                content=f"# Kubernetes Deployment\n# Generated from manifest\n\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {agent_name}\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: {agent_name}\n  template:\n    metadata:\n      labels:\n        app: {agent_name}\n    spec:\n      containers:\n      - name: {agent_name}\n        image: {agent_name}:latest\n",
                description="Kubernetes deployment",
            ),
            # Root files
            FileDefinition(
                path=str(agent_dir / "pyproject.toml"),
                content=f"""[project]
name = "{agent_name}"
version = "1.0.0"
description = "OSSA-compliant agent"
requires-python = ">=3.9"
dependencies = [
    "ossa-sdk>=0.3.5",
    "pydantic>=2.0.0",
    "fastapi>=0.100.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "mypy>=1.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
""",
                description="pyproject.toml",
            ),
            FileDefinition(
                path=str(agent_dir / "AGENTS.md"),
                content="# AGENTS.md\n\n## Dev environment tips\n\n- Use Python 3.9+\n- Run `pip install -e .` to install dependencies\n- Run `pytest` to run tests\n\n## Testing instructions\n\n- Run `pytest` for unit tests\n- Run `pytest tests/integration` for integration tests\n\n## PR instructions\n\n- Use conventional commits\n- Run `mypy .` before committing\n",
                description="AGENTS.md (AAIF standard)",
            ),
            FileDefinition(
                path=str(agent_dir / "README.md"),
                content=f"""# {agent_name}

OSSA-compliant agent following OpenAPI-first, API-first, Pydantic, CRUD, SOLID, and DRY principles.

## Structure

- `manifest.ossa.yaml` - Single source of truth
- `openapi.yaml` - Generated from manifest
- `pydantic_models.py` - Generated from OpenAPI
- `client.py` - Generated from OpenAPI

## Usage

```bash
# Validate manifest
ossa validate manifest.ossa.yaml

# Generate OpenAPI
ossa generate openapi manifest.ossa.yaml

# Generate Pydantic models
ossa generate pydantic openapi.yaml

# Generate API client
ossa generate client openapi.yaml
```
""",
                description="README.md",
            ),
        ]

        return AgentFolderStructure(
            agent_name=agent_name,
            base_path=base_path,
            directories=directories,
            files=files,
        )

    def create_structure(
        self, structure: AgentFolderStructure, overwrite: bool = False
    ) -> None:
        """Create folder structure on filesystem"""
        # Create directories
        for dir_path in structure.directories:
            dir_obj = Path(dir_path)
            if dir_obj.exists() and not overwrite:
                continue
            dir_obj.mkdir(parents=True, exist_ok=True)

        # Create files
        for file_def in structure.files:
            file_path = Path(file_def.path)
            if file_path.exists() and not overwrite:
                continue
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(file_def.content, encoding="utf-8")

    def validate_structure(
        self, agent_dir: str
    ) -> Dict[str, any]:
        """Validate folder structure"""
        errors: List[str] = []
        required_dirs = [
            "prompts",
            "tools",
            "config",
            "api",
            "src",
            "tests",
            "docs",
        ]
        required_files = [
            "manifest.ossa.yaml",
            "pyproject.toml",
            "README.md",
        ]

        agent_path = Path(agent_dir)

        for dir_name in required_dirs:
            dir_path = agent_path / dir_name
            if not dir_path.exists():
                errors.append(f"Missing directory: {dir_name}")

        for file_name in required_files:
            file_path = agent_path / file_name
            if not file_path.exists():
                errors.append(f"Missing file: {file_name}")

        return {"valid": len(errors) == 0, "errors": errors}
