import type { ExportTarget, ExportResult, GeneratedFile } from '../types.js';

/** Client-side export engine. Generates platform-specific scaffolding from OSSA manifests. */
export class ExportEngine {
  /** Export a manifest to a target platform */
  export(
    manifest: Record<string, unknown>,
    target: ExportTarget,
  ): ExportResult {
    const metadata = manifest.metadata as Record<string, unknown>;
    const spec = manifest.spec as Record<string, unknown>;
    const name = (metadata?.name as string) ?? 'agent';
    const safeName = name.replace(/[^a-zA-Z0-9_-]/g, '-');

    const generator = this.getGenerator(target);
    const files = generator(manifest, safeName, spec);

    return { target, files, manifest };
  }

  /** List all supported export targets */
  getTargets(): ExportTarget[] {
    return [
      'docker',
      'kubernetes',
      'langchain',
      'crewai',
      'anthropic',
      'openai',
      'npm',
      'mcp',
      'drupal',
      'gitlab-duo',
      'vercel-ai',
      'kagent',
      'langgraph',
      'autogen',
    ];
  }

  private getGenerator(
    target: ExportTarget,
  ): (
    manifest: Record<string, unknown>,
    name: string,
    spec: Record<string, unknown>,
  ) => GeneratedFile[] {
    switch (target) {
      case 'docker':
        return this.generateDocker;
      case 'kubernetes':
        return this.generateKubernetes;
      case 'npm':
        return this.generateNpm;
      case 'anthropic':
        return this.generateAnthropic;
      case 'mcp':
        return this.generateMcp;
      default:
        return this.generateGeneric;
    }
  }

  private generateDocker(
    manifest: Record<string, unknown>,
    name: string,
    spec: Record<string, unknown>,
  ): GeneratedFile[] {
    const tools = (spec?.tools as { name: string; type: string }[]) ?? [];
    const llm = spec?.llm as Record<string, unknown> | undefined;

    const files: GeneratedFile[] = [
      {
        path: `${name}.ossa.yaml`,
        content: `# Source OSSA manifest\n# Generated by @bluefly/ossa-engine\napiVersion: ${manifest.apiVersion}\nkind: ${manifest.kind}\nmetadata:\n  name: ${name}\nspec:\n  role: "${spec?.role ?? 'agent'}"\n`,
        language: 'yaml',
      },
      {
        path: 'Dockerfile',
        content: `FROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --production\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY --from=builder /app/node_modules ./node_modules\nCOPY --from=builder /app/package.json ./\nEXPOSE 3000\nHEALTHCHECK CMD wget -qO- http://localhost:3000/health || exit 1\nCMD ["node", "dist/agent.js"]\n`,
        language: 'dockerfile',
      },
      {
        path: 'docker-compose.yml',
        content: `services:\n  ${name}:\n    build: .\n    ports:\n      - "3000:3000"\n    environment:\n      - NODE_ENV=production\n${llm?.provider ? `      - LLM_PROVIDER=${llm.provider}\n      - LLM_MODEL=${llm.model ?? ''}\n` : ''}    restart: unless-stopped\n`,
        language: 'yaml',
      },
      {
        path: 'src/agent.ts',
        content: `import { config } from './config.js';\n\nasync function main() {\n  console.log(\`Starting \${config.name} agent...\`);\n  // Agent runtime entry point\n}\n\nmain().catch(console.error);\n`,
        language: 'typescript',
      },
      {
        path: 'src/config.ts',
        content: `export const config = {\n  name: '${name}',\n  role: '${spec?.role ?? 'agent'}',\n  llm: {\n    provider: process.env.LLM_PROVIDER ?? '${llm?.provider ?? 'anthropic'}',\n    model: process.env.LLM_MODEL ?? '${llm?.model ?? 'claude-sonnet-4-5-20250929'}',\n  },\n} as const;\n`,
        language: 'typescript',
      },
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name,
            version: '1.0.0',
            type: 'module',
            scripts: { build: 'tsc', start: 'node dist/agent.js' },
            dependencies: { '@anthropic-ai/sdk': '^0.71.0' },
            devDependencies: { typescript: '^5.9.3' },
          },
          null,
          2,
        ),
        language: 'json',
      },
      {
        path: 'tsconfig.json',
        content: JSON.stringify(
          {
            compilerOptions: {
              target: 'ES2022',
              module: 'ESNext',
              moduleResolution: 'bundler',
              outDir: 'dist',
              rootDir: 'src',
              strict: true,
            },
            include: ['src'],
          },
          null,
          2,
        ),
        language: 'json',
      },
    ];

    // Add tool files
    for (const tool of tools) {
      files.push({
        path: `src/tools/${tool.name.replace(/[^a-zA-Z0-9_-]/g, '-')}.ts`,
        content: `// Tool: ${tool.name} (${tool.type})\nexport async function ${tool.name.replace(/[^a-zA-Z0-9_]/g, '')}() {\n  // Tool implementation\n}\n`,
        language: 'typescript',
      });
    }

    files.push({
      path: 'tests/agent.test.ts',
      content: `import { describe, it, expect } from 'vitest';\nimport { config } from '../src/config.js';\n\ndescribe('${name}', () => {\n  it('has correct config', () => {\n    expect(config.name).toBe('${name}');\n  });\n});\n`,
      language: 'typescript',
    });

    return files;
  }

  private generateKubernetes(
    manifest: Record<string, unknown>,
    name: string,
    spec: Record<string, unknown>,
  ): GeneratedFile[] {
    const llm = spec?.llm as Record<string, unknown> | undefined;
    return [
      {
        path: `${name}.ossa.yaml`,
        content: `apiVersion: ${manifest.apiVersion}\nkind: ${manifest.kind}\nmetadata:\n  name: ${name}\n`,
        language: 'yaml',
      },
      {
        path: 'k8s/deployment.yaml',
        content: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ${name}\n  labels:\n    app: ${name}\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: ${name}\n  template:\n    metadata:\n      labels:\n        app: ${name}\n    spec:\n      containers:\n      - name: ${name}\n        image: ${name}:latest\n        ports:\n        - containerPort: 3000\n        env:\n        - name: LLM_PROVIDER\n          value: "${llm?.provider ?? 'anthropic'}"\n        resources:\n          limits:\n            memory: "512Mi"\n            cpu: "500m"\n`,
        language: 'yaml',
      },
      {
        path: 'k8s/service.yaml',
        content: `apiVersion: v1\nkind: Service\nmetadata:\n  name: ${name}\nspec:\n  selector:\n    app: ${name}\n  ports:\n  - port: 80\n    targetPort: 3000\n`,
        language: 'yaml',
      },
    ];
  }

  private generateNpm(
    manifest: Record<string, unknown>,
    name: string,
  ): GeneratedFile[] {
    return [
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name: `@ossa/${name}`,
            version: '1.0.0',
            type: 'module',
            main: 'dist/index.js',
            types: 'dist/index.d.ts',
            scripts: { build: 'tsc', test: 'vitest run' },
          },
          null,
          2,
        ),
        language: 'json',
      },
      {
        path: 'src/index.ts',
        content: `export { agent } from './agent.js';\n`,
        language: 'typescript',
      },
      {
        path: 'src/agent.ts',
        content: `export const agent = {\n  name: '${name}',\n  version: '${(manifest.metadata as Record<string, unknown>)?.version ?? '1.0.0'}',\n};\n`,
        language: 'typescript',
      },
    ];
  }

  private generateAnthropic(
    _manifest: Record<string, unknown>,
    name: string,
    spec: Record<string, unknown>,
  ): GeneratedFile[] {
    const tools = (spec?.tools as { name: string }[]) ?? [];
    return [
      {
        path: 'src/agent.ts',
        content: `import Anthropic from '@anthropic-ai/sdk';\n\nconst client = new Anthropic();\n\nexport async function run(input: string) {\n  const response = await client.messages.create({\n    model: '${(spec?.llm as Record<string, unknown>)?.model ?? 'claude-sonnet-4-5-20250929'}',\n    max_tokens: 4096,\n    system: '${spec?.role ?? name}',\n    messages: [{ role: 'user', content: input }],\n${tools.length ? `    tools: [${tools.map((t) => `{ name: '${t.name}', description: '${t.name} tool' }`).join(', ')}],\n` : ''}  });\n  return response;\n}\n`,
        language: 'typescript',
      },
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name,
            version: '1.0.0',
            type: 'module',
            dependencies: { '@anthropic-ai/sdk': '^0.71.0' },
          },
          null,
          2,
        ),
        language: 'json',
      },
    ];
  }

  private generateMcp(
    _manifest: Record<string, unknown>,
    name: string,
    spec: Record<string, unknown>,
  ): GeneratedFile[] {
    const tools = (spec?.tools as { name: string }[]) ?? [];
    return [
      {
        path: 'src/server.ts',
        content: `import { Server } from '@modelcontextprotocol/sdk/server/index.js';\nimport { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';\n\nconst server = new Server({ name: '${name}', version: '1.0.0' }, { capabilities: { tools: {} } });\n\n${tools.map((t) => `server.setRequestHandler('tools/call', async (request) => {\n  if (request.params.name === '${t.name}') {\n    return { content: [{ type: 'text', text: 'Result from ${t.name}' }] };\n  }\n});`).join('\n\n')}\n\nconst transport = new StdioServerTransport();\nawait server.connect(transport);\n`,
        language: 'typescript',
      },
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name: `@ossa/${name}-mcp`,
            version: '1.0.0',
            type: 'module',
            dependencies: { '@modelcontextprotocol/sdk': '^0.6.0' },
          },
          null,
          2,
        ),
        language: 'json',
      },
    ];
  }

  private generateGeneric(
    manifest: Record<string, unknown>,
    name: string,
  ): GeneratedFile[] {
    return [
      {
        path: `${name}.ossa.yaml`,
        content: `# OSSA Agent Manifest\napiVersion: ${manifest.apiVersion}\nkind: ${manifest.kind}\nmetadata:\n  name: ${name}\n`,
        language: 'yaml',
      },
      {
        path: 'src/agent.ts',
        content: `// Agent: ${name}\n// Generated by @bluefly/ossa-engine\nexport const agent = { name: '${name}' };\n`,
        language: 'typescript',
      },
    ];
  }
}
