/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * Platform health check
     * @description OSSA v0.1.8 compliant health check with detailed status
     */
    get: operations["getHealth"];
  };
  "/version": {
    /** Get platform version info */
    get: operations["getVersion"];
  };
  "/agents": {
    /**
     * List registered agents
     * @description Get all agents in the registry with filtering and pagination
     */
    get: operations["listAgents"];
    /**
     * Register new agent
     * @description Register a new OSSA v0.1.8 compliant agent
     */
    post: operations["registerAgent"];
  };
  "/agents/{agentId}": {
    /** Get agent details */
    get: operations["getAgent"];
    /** Update agent */
    put: operations["updateAgent"];
    /** Unregister agent */
    delete: operations["unregisterAgent"];
  };
  "/discover": {
    /**
     * Discover agents by capabilities
     * @description Universal Agent Discovery Protocol (UADP) compatible endpoint
     */
    get: operations["discoverAgents"];
  };
  "/metrics": {
    /** Get platform metrics */
    get: operations["getMetrics"];
  };
  "/graphql": {
    /**
     * GraphQL API endpoint
     * @description Execute GraphQL queries, mutations, and subscriptions
     */
    post: operations["graphql"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    HealthStatus: {
      /** @enum {string} */
      status: "healthy" | "degraded" | "unhealthy";
      version: string;
      ossa_version?: string;
      uptime?: number;
      services?: {
        [key: string]: "healthy" | "degraded" | "unhealthy";
      };
      /** Format: date-time */
      timestamp: string;
    };
    VersionInfo: {
      api: string;
      ossa: string;
      platform: string;
      build?: string;
      commit?: string;
    };
    Agent: {
      /** Format: uuid */
      id: string;
      name: string;
      version: string;
      description?: string;
      spec: components["schemas"]["AgentSpec"];
      status?: components["schemas"]["AgentStatus"];
      /** Format: date-time */
      registered_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    AgentSpec: {
      /** @enum {string} */
      conformance_tier: "core" | "governed" | "advanced";
      /** @enum {string} */
      class: "general" | "specialist" | "workflow" | "integration";
      /** @enum {string} */
      category?: "assistant" | "tool" | "service" | "coordinator";
      capabilities: {
        primary: string[];
        secondary?: string[];
      };
      protocols?: components["schemas"]["Protocol"][];
      endpoints?: {
        /** Format: uri */
        health: string;
        /** Format: uri */
        capabilities?: string;
        /** Format: uri */
        api?: string;
      };
    };
    Protocol: {
      /** @enum {string} */
      name: "openapi" | "mcp" | "uadp" | "graphql";
      version: string;
      required: boolean;
      extensions?: string[];
    };
    AgentStatus: {
      /** @enum {string} */
      health: "healthy" | "degraded" | "unhealthy" | "unknown";
      /** Format: date-time */
      last_seen: string;
      metrics?: {
        requests_per_minute?: number;
        average_response_time?: number;
        error_rate?: number;
      };
    };
    AgentRegistration: {
      name: string;
      version: string;
      description?: string;
      /** Format: uri */
      endpoint: string;
      spec: components["schemas"]["AgentSpec"];
    };
    AgentUpdate: {
      version?: string;
      description?: string;
      /** Format: uri */
      endpoint?: string;
      spec?: components["schemas"]["AgentSpec"];
    };
    AgentList: {
      agents: components["schemas"]["Agent"][];
      total: number;
      limit: number;
      offset: number;
    };
    DiscoveryResult: {
      agents: components["schemas"]["Agent"][];
      query: {
        capabilities?: string[];
        domain?: string;
        tier?: string;
      };
      total?: number;
    };
    PlatformMetrics: {
      /** Format: date-time */
      timestamp?: string;
      timeframe?: string;
      agents?: {
        total?: number;
        active?: number;
        by_tier?: {
          [key: string]: number;
        };
      };
      requests?: {
        total?: number;
        success_rate?: number;
        average_response_time?: number;
      };
      errors?: {
          code?: string;
          message?: string;
          count?: number;
        }[];
    };
  };
  responses: {
    /** @description Bad request */
    BadRequest: {
      content: {
        "application/json": {
          error?: string;
          details?: Record<string, never>;
        };
      };
    };
    /** @description Resource not found */
    NotFound: {
      content: {
        "application/json": {
          /** @example Agent not found */
          error?: string;
        };
      };
    };
    /** @description Internal server error */
    ServerError: {
      content: {
        "application/json": {
          error?: string;
          request_id?: string;
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Platform health check
   * @description OSSA v0.1.8 compliant health check with detailed status
   */
  getHealth: {
    responses: {
      /** @description Platform is healthy */
      200: {
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
    };
  };
  /** Get platform version info */
  getVersion: {
    responses: {
      /** @description Version information */
      200: {
        content: {
          "application/json": components["schemas"]["VersionInfo"];
        };
      };
    };
  };
  /**
   * List registered agents
   * @description Get all agents in the registry with filtering and pagination
   */
  listAgents: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        class?: "general" | "specialist" | "workflow" | "integration";
        tier?: "core" | "governed" | "advanced";
      };
    };
    responses: {
      /** @description List of agents */
      200: {
        content: {
          "application/json": components["schemas"]["AgentList"];
        };
      };
    };
  };
  /**
   * Register new agent
   * @description Register a new OSSA v0.1.8 compliant agent
   */
  registerAgent: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentRegistration"];
      };
    };
    responses: {
      /** @description Agent registered successfully */
      201: {
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description Agent already exists */
      409: {
        content: never;
      };
    };
  };
  /** Get agent details */
  getAgent: {
    parameters: {
      path: {
        agentId: string;
      };
    };
    responses: {
      /** @description Agent details */
      200: {
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /** Update agent */
  updateAgent: {
    parameters: {
      path: {
        agentId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentUpdate"];
      };
    };
    responses: {
      /** @description Agent updated */
      200: {
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /** Unregister agent */
  unregisterAgent: {
    parameters: {
      path: {
        agentId: string;
      };
    };
    responses: {
      /** @description Agent unregistered */
      204: {
        content: never;
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Discover agents by capabilities
   * @description Universal Agent Discovery Protocol (UADP) compatible endpoint
   */
  discoverAgents: {
    parameters: {
      query?: {
        capabilities?: string[];
        domain?: string;
        tier?: "core" | "governed" | "advanced";
      };
    };
    responses: {
      /** @description Discovered agents */
      200: {
        content: {
          "application/json": components["schemas"]["DiscoveryResult"];
        };
      };
    };
  };
  /** Get platform metrics */
  getMetrics: {
    parameters: {
      query?: {
        timeframe?: "1h" | "6h" | "24h" | "7d" | "30d";
      };
    };
    responses: {
      /** @description Platform metrics */
      200: {
        content: {
          "application/json": components["schemas"]["PlatformMetrics"];
        };
      };
    };
  };
  /**
   * GraphQL API endpoint
   * @description Execute GraphQL queries, mutations, and subscriptions
   */
  graphql: {
    requestBody: {
      content: {
        "application/json": {
          query: string;
          variables?: Record<string, never>;
          operationName?: string;
        };
      };
    };
    responses: {
      /** @description GraphQL response */
      200: {
        content: {
          "application/json": {
            data?: Record<string, never>;
            errors?: Record<string, never>[];
          };
        };
      };
    };
  };
}
