#!/usr/bin/env node

/**
 * Sync version from @bluefly/openstandardagents package
 *
 * The installed npm package is the single source of truth for version.
 * This script generates version.ts that imports from the package.
 *
 * Run: npm run sync-version
 * Automatically runs on: npm run dev, npm run build
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// version.ts is in website/lib/
const versionTsPath = path.join(__dirname, '..', '..', 'website', 'lib', 'version.ts');

// Look for package in multiple locations (pnpm workspace structure)
const rootDir = path.join(__dirname, '..', '..');
const websiteDir = path.join(rootDir, 'website');

function findPackage() {
  const locations = [
    path.join(rootDir, 'node_modules', '@bluefly', 'openstandardagents', 'package.json'),
    path.join(websiteDir, 'node_modules', '@bluefly', 'openstandardagents', 'package.json'),
  ];

  for (const loc of locations) {
    if (fs.existsSync(loc)) {
      try {
        return JSON.parse(fs.readFileSync(loc, 'utf-8'));
      } catch (e) {
        console.error('Error parsing package.json at', loc, ':', e.message);
        continue;
      }
    }
  }
  return null;
}

async function syncVersion() {
  let version;
  let source;

  const ossaPkg = findPackage();
  if (ossaPkg) {
    version = ossaPkg.version;
    source = '@bluefly/openstandardagents package';
    console.log(`📦 Using version ${version} from ${source}`);
  } else {
    console.error('❌ @bluefly/openstandardagents package not installed');
    console.error('   Run: npm install @bluefly/openstandardagents');
    console.error('   Or:  pnpm add @bluefly/openstandardagents');
    process.exit(1);
  }

  // Generate version.ts with static values from the installed package
  const versionTsContent = `// OSSA version constants
// Synced from @bluefly/openstandardagents@${version} package
// AUTO-GENERATED by sync-version.js - DO NOT EDIT DIRECTLY

import versionsData from './versions.json';

// Version from installed @bluefly/openstandardagents package
export const OSSA_VERSION = "${version}";
export const OSSA_VERSION_TAG = "v${version}";
export const OSSA_API_VERSION = "ossa/v${version}";
export const OSSA_SCHEMA_VERSION = "${version}";

// Display version for marketing
export const OSSA_DISPLAY_VERSION = "${version}";
export const OSSA_DISPLAY_VERSION_TAG = "v${version}";

// Aliases for backward compatibility
export const STABLE_VERSION = OSSA_VERSION;
export const STABLE_VERSION_TAG = OSSA_VERSION_TAG;

// Type definitions for version data
export interface VersionInfo {
  version: string;
  tag: string;
  apiVersion: string;
  type: 'stable' | 'dev' | 'prerelease';
  published: boolean;
  available: boolean;
}

// Version data from versions.json
export const STABLE_VERSIONS = (versionsData.all as VersionInfo[]).filter((v) => v.type === 'stable');
export const DEV_VERSIONS = (versionsData.all as VersionInfo[]).filter((v) => v.type === 'dev' || v.type === 'prerelease');
export const ALL_VERSIONS = versionsData.all as VersionInfo[];
export const DEV_VERSION_TAG = versionsData.dev ? \`v\${versionsData.dev}\` : undefined;

// Utility to get version info from local versions.json
export function getVersionInfo(version: string): VersionInfo | undefined {
  return (versionsData.all as VersionInfo[]).find((v) => v.version === version);
}

// Utility to get schema path
export function getSchemaPath(ver = OSSA_VERSION): string {
  return \`/schemas/ossa-\${ver}.schema.json\`;
}

// Utility to get spec path
export function getSpecPath(ver = OSSA_VERSION): string {
  return \`/spec/v\${ver}/ossa-\${ver}.schema.json\`;
}
`;

  fs.writeFileSync(versionTsPath, versionTsContent);
  console.log(`✅ Generated version.ts using ${source} (v${version})`);
}

syncVersion().catch(error => {
  console.error('❌ Error syncing version:', error.message);
  process.exit(1);
});
