/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = T | U extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only]
  ? Only
  : T extends [infer A, infer B, ...infer Rest]
    ? OneOf<[XOR<A, B>, ...Rest]>
    : never;

export interface paths {
  '/agents': {
    /**
     * List all agents
     * @description Retrieve a paginated list of agents with advanced filtering and sorting capabilities.
     *
     * Supports:
     * - Type-based filtering with inheritance hierarchy
     * - Capability-based search with fuzzy matching
     * - Status filtering (active, inactive, error, deploying)
     * - Creation date range queries
     * - Performance metric filtering
     */
    get: operations['listAgents'];
    /**
     * Create a new agent
     * @description Create a new agent with comprehensive validation and automatic capability inference.
     *
     * Features:
     * - **Polymorphic agent types** with discriminator-based validation
     * - **Automatic capability detection** from provided specifications
     * - **Version conflict resolution** with semantic versioning
     * - **Dependency validation** against existing agents
     * - **Resource quota enforcement** per organization
     * - **Async creation** with webhook notifications
     */
    post: operations['createAgent'];
  };
  '/agents/{agent_id}': {
    /**
     * Get agent details
     * @description Retrieve detailed information about a specific agent including:
     * - Current status and health metrics
     * - Performance statistics and SLA compliance
     * - Capability matrix and dependencies
     * - Recent execution history
     * - Configuration and metadata
     */
    get: operations['getAgent'];
    /**
     * Update agent
     * @description Update an existing agent with full replacement semantics.
     *
     * Supports:
     * - **Atomic updates** with rollback on failure
     * - **Version-aware updates** with optimistic locking
     * - **Capability migration** with backwards compatibility
     * - **Hot updates** for non-breaking changes
     * - **Blue-green deployment** for breaking changes
     */
    put: operations['updateAgent'];
    /**
     * Delete agent
     * @description Delete an agent with comprehensive cleanup and dependency management.
     *
     * Features:
     * - **Graceful shutdown** with configurable timeout
     * - **Dependency validation** to prevent orphaned workflows
     * - **Data retention policies** with configurable periods
     * - **Audit trail preservation** for compliance
     * - **Cascading deletion** of related resources
     */
    delete: operations['deleteAgent'];
    /**
     * Partially update agent
     * @description Perform partial updates to an agent using JSON Patch (RFC 6902) operations.
     *
     * Supports atomic patch operations:
     * - `add` - Add new properties or array elements
     * - `remove` - Remove properties or array elements
     * - `replace` - Replace existing values
     * - `move` - Move values within the document
     * - `copy` - Copy values within the document
     * - `test` - Test values before applying other operations
     */
    patch: operations['patchAgent'];
    parameters: {
      path: {
        agent_id: components['parameters']['AgentIdParam'];
      };
    };
  };
  '/agents/{agent_id}/execute': {
    /**
     * Execute agent operation
     * @description Execute a specific operation on an agent with comprehensive input validation
     * and execution tracking.
     *
     * Execution Features:
     * - **Input schema validation** against agent capabilities
     * - **Execution context isolation** for security
     * - **Real-time progress tracking** via WebSocket
     * - **Result caching** with configurable TTL
     * - **Execution history** and audit logging
     * - **Resource quotas** and throttling
     */
    post: operations['executeAgent'];
    parameters: {
      path: {
        agent_id: components['parameters']['AgentIdParam'];
      };
    };
  };
  '/agents/{agent_id}/executions/{execution_id}': {
    /**
     * Get execution status
     * @description Retrieve the status and results of an asynchronous execution.
     *
     * Provides:
     * - **Real-time status** (pending, running, completed, failed)
     * - **Progress indicators** with percentage completion
     * - **Intermediate results** for long-running operations
     * - **Resource usage metrics** (CPU, memory, duration)
     * - **Error details** with stack traces and context
     */
    get: operations['getExecutionStatus'];
    parameters: {
      path: {
        agent_id: components['parameters']['AgentIdParam'];
        execution_id: components['parameters']['ExecutionIdParam'];
      };
    };
  };
  '/specifications': {
    /**
     * List OpenAPI specifications
     * @description Retrieve all OpenAPI specifications with metadata and validation status.
     *
     * Features:
     * - **Version history** tracking with semantic versioning
     * - **Validation status** against OpenAPI 3.1 schema
     * - **Dependency mapping** between specifications
     * - **Usage analytics** and adoption metrics
     */
    get: operations['listSpecifications'];
  };
  '/specifications/{spec_id}': {
    /**
     * Get specification
     * @description Retrieve a specific OpenAPI specification with full content and metadata
     */
    get: operations['getSpecification'];
    parameters: {
      path: {
        spec_id: components['parameters']['SpecIdParam'];
      };
    };
  };
}

export interface webhooks {
  agentCreated: {
    /**
     * Agent created notification
     * @description Triggered when a new agent is successfully created
     */
    post: operations['handleAgentCreated'];
  };
  agentStatusChanged: {
    /**
     * Agent status change notification
     * @description Triggered when an agent's status changes
     */
    post: operations['handleAgentStatusChanged'];
  };
  executionCompleted: {
    /**
     * Execution completed notification
     * @description Triggered when an agent execution completes
     */
    post: operations['handleExecutionCompleted'];
  };
}

export interface components {
  schemas: {
    Agent: {
      /**
       * @description Unique agent identifier following DNS naming conventions
       * @example agent-001
       */
      id: string;
      type: components['schemas']['AgentType'];
      /**
       * @description Human-readable agent name
       * @example Data Processing Agent
       */
      name: string;
      /** @example Processes incoming data streams with validation and transformation */
      description?: string;
      /**
       * @description Semantic version following SemVer specification
       * @example 1.2.3
       */
      version: string;
      status: components['schemas']['AgentStatus'];
      /**
       * @description List of capabilities this agent provides
       * @example [
       *   "data-processing",
       *   "validation",
       *   "transformation"
       * ]
       */
      capabilities: string[];
      /** @description Agent-specific configuration parameters */
      configuration?: {
        [key: string]: unknown;
      };
      metadata?: components['schemas']['AgentMetadata'];
      /**
       * Format: date-time
       * @description Agent creation timestamp in ISO 8601 format
       * @example 2025-01-15T10:30:00Z
       */
      created_at: string;
      /**
       * Format: date-time
       * @description Last update timestamp in ISO 8601 format
       * @example 2025-01-15T14:30:00Z
       */
      updated_at: string;
      metrics?: components['schemas']['AgentMetrics'];
    };
    WorkerAgent: {
      type: 'worker';
    } & Omit<components['schemas']['Agent'], 'type'> & {
        /** @constant */
        type?: 'worker';
        configuration?: {
          /** @default 10 */
          max_concurrent_tasks?: number;
          /** @default 300 */
          timeout_seconds?: number;
          /** @default 3 */
          retry_attempts?: number;
          [key: string]: unknown;
        };
        /**
         * @description Worker specialization type
         * @enum {string}
         */
        specialization: 'data-processing' | 'api-integration' | 'file-handling' | 'validation';
      };
    OrchestratorAgent: {
      type: 'orchestrator';
    } & Omit<components['schemas']['Agent'], 'type'> & {
        /** @constant */
        type?: 'orchestrator';
        configuration?: {
          /** @default 5 */
          max_concurrent_workflows?: number;
          /** @default 60 */
          workflow_timeout_minutes?: number;
          /** @default true */
          enable_parallel_execution?: boolean;
          [key: string]: unknown;
        };
        /** @description List of agent IDs this orchestrator manages */
        managed_agents?: string[];
      };
    CriticAgent: {
      type: 'critic';
    } & Omit<components['schemas']['Agent'], 'type'> & {
        /** @constant */
        type?: 'critic';
        configuration?: {
          /** @default 80 */
          quality_threshold?: number;
          /** @default false */
          automated_fixes?: boolean;
          review_categories?: ('code-quality' | 'security' | 'performance' | 'compliance')[];
          [key: string]: unknown;
        };
      };
    JudgeAgent: {
      type: 'judge';
    } & Omit<components['schemas']['Agent'], 'type'> & {
        /** @constant */
        type?: 'judge';
        configuration?: {
          /**
           * @default majority
           * @enum {string}
           */
          decision_model?: 'consensus' | 'majority' | 'weighted' | 'ai-assisted';
          /** @default 0.8 */
          confidence_threshold?: number;
          [key: string]: unknown;
        };
      };
    MonitorAgent: {
      type: 'monitor';
    } & Omit<components['schemas']['Agent'], 'type'> & {
        /** @constant */
        type?: 'monitor';
        configuration?: {
          /** @default 60 */
          monitoring_interval_seconds?: number;
          alert_thresholds?: {
            /** @default 80 */
            cpu_percent?: number;
            /** @default 80 */
            memory_percent?: number;
            /** @default 5 */
            error_rate_percent?: number;
          };
          [key: string]: unknown;
        };
      };
    GovernorAgent: {
      type: 'governor';
    } & Omit<components['schemas']['Agent'], 'type'> & {
        /** @constant */
        type?: 'governor';
        configuration?: {
          /**
           * @default strict
           * @enum {string}
           */
          policy_enforcement_level?: 'strict' | 'moderate' | 'permissive';
          compliance_frameworks?: ('ISO42001' | 'NIST-AI-RMF' | 'EU-AI-ACT' | 'SOX' | 'HIPAA')[];
          [key: string]: unknown;
        };
      };
    /**
     * @description Agent type classification:
     * - **worker**: Task execution agents
     * - **orchestrator**: Workflow coordination agents
     * - **critic**: Quality control and review agents
     * - **judge**: Decision-making agents
     * - **monitor**: System observation agents
     * - **governor**: Policy enforcement agents
     *
     * @enum {string}
     */
    AgentType: 'worker' | 'orchestrator' | 'critic' | 'judge' | 'monitor' | 'governor';
    /**
     * @description Current agent status:
     * - **active**: Agent is running and available
     * - **inactive**: Agent is stopped but can be started
     * - **error**: Agent has encountered an error
     * - **deploying**: Agent is being deployed
     * - **maintenance**: Agent is under maintenance
     * - **deprecated**: Agent is deprecated and should not be used
     *
     * @enum {string}
     */
    AgentStatus: 'active' | 'inactive' | 'error' | 'deploying' | 'maintenance' | 'deprecated';
    AgentMetadata: {
      /** @example John Doe <john@example.com> */
      author?: string;
      /** @example Acme Corporation */
      organization?: string;
      /**
       * @example [
       *   "ml",
       *   "data",
       *   "production"
       * ]
       */
      tags?: string[];
      /**
       * Format: uri
       * @example https://docs.example.com/agents/data-processor
       */
      documentation_url?: string;
      /**
       * Format: uri
       * @example https://github.com/example/data-processor-agent
       */
      source_repository?: string;
      /** @example MIT */
      license?: string;
      /**
       * @description Cost in USD per execution
       * @example 0.001
       */
      cost_per_execution?: number;
      [key: string]: unknown;
    };
    AgentMetrics: {
      /** @example 12543 */
      total_executions?: number;
      /** @example 12123 */
      successful_executions?: number;
      /** @example 420 */
      failed_executions?: number;
      /** @example 1250.5 */
      average_execution_time_ms?: number;
      /**
       * Format: date-time
       * @example 2025-01-15T14:25:00Z
       */
      last_execution_at?: string;
      /** @example 96.65 */
      success_rate_percent?: number;
      /** @example 23.5 */
      cpu_usage_percent?: number;
      /** @example 512.8 */
      memory_usage_mb?: number;
    };
    CreateAgentRequest: {
      type: components['schemas']['AgentType'];
      name: string;
      description?: string;
      /** @default 1.0.0 */
      version?: string;
      capabilities: string[];
      configuration?: {
        [key: string]: unknown;
      };
      metadata?: components['schemas']['AgentMetadata'];
      /**
       * Format: uri
       * @description URL to receive status change notifications
       */
      webhook_url?: string;
    };
    CreateWorkerAgentRequest: {
      type: 'worker';
    } & Omit<components['schemas']['CreateAgentRequest'], 'type'> & {
        /** @constant */
        type?: 'worker';
        /** @enum {string} */
        specialization: 'data-processing' | 'api-integration' | 'file-handling' | 'validation';
        configuration?: {
          /** @default 10 */
          max_concurrent_tasks?: number;
          /** @default 300 */
          timeout_seconds?: number;
          [key: string]: unknown;
        };
      };
    CreateOrchestratorAgentRequest: {
      type: 'orchestrator';
    } & Omit<components['schemas']['CreateAgentRequest'], 'type'> & {
        /** @constant */
        type?: 'orchestrator';
        configuration?: {
          /** @default 5 */
          max_concurrent_workflows?: number;
          /** @default 60 */
          workflow_timeout_minutes?: number;
          [key: string]: unknown;
        };
      };
    CreateCriticAgentRequest: {
      type: 'critic';
    } & Omit<components['schemas']['CreateAgentRequest'], 'type'> & {
        /** @constant */
        type?: 'critic';
        configuration?: {
          /** @default 80 */
          quality_threshold?: number;
          /** @default false */
          automated_fixes?: boolean;
          [key: string]: unknown;
        };
      };
    CreateJudgeAgentRequest: {
      type: 'judge';
    } & Omit<components['schemas']['CreateAgentRequest'], 'type'> & {
        /** @constant */
        type?: 'judge';
        configuration?: {
          /**
           * @default majority
           * @enum {string}
           */
          decision_model?: 'consensus' | 'majority' | 'weighted' | 'ai-assisted';
          [key: string]: unknown;
        };
      };
    CreateMonitorAgentRequest: {
      type: 'monitor';
    } & Omit<components['schemas']['CreateAgentRequest'], 'type'> & {
        /** @constant */
        type?: 'monitor';
        configuration?: {
          /** @default 60 */
          monitoring_interval_seconds?: number;
          [key: string]: unknown;
        };
      };
    CreateGovernorAgentRequest: {
      type: 'governor';
    } & Omit<components['schemas']['CreateAgentRequest'], 'type'> & {
        /** @constant */
        type?: 'governor';
        configuration?: {
          /**
           * @default strict
           * @enum {string}
           */
          policy_enforcement_level?: 'strict' | 'moderate' | 'permissive';
          [key: string]: unknown;
        };
      };
    UpdateAgentRequest: {
      name?: string;
      description?: string;
      version?: string;
      capabilities?: string[];
      configuration?: {
        [key: string]: unknown;
      };
      metadata?: components['schemas']['AgentMetadata'];
      /** @description Expected current version for optimistic locking */
      expected_version?: string;
    };
    AgentListResponse: {
      agents: components['schemas']['Agent'][];
      pagination: components['schemas']['PaginationInfo'];
      /** @description Applied filters for this query */
      filters?: {
        [key: string]: unknown;
      };
    };
    PaginationInfo: {
      /** @example 1 */
      page: number;
      /** @example 20 */
      limit: number;
      /** @example 157 */
      total: number;
      /** @example true */
      has_next: boolean;
      /** @example false */
      has_previous: boolean;
    };
    ExecutionRequest: {
      /**
       * @description Name of the operation to execute
       * @example process_data
       */
      operation: string;
      /** @description Input parameters for the operation */
      input: {
        [key: string]: unknown;
      };
      /** @description Execution context and metadata */
      context?: {
        /** @example user-123 */
        user_id?: string;
        /** @example org-456 */
        organization_id?: string;
        /** @example corr-789 */
        correlation_id?: string;
        /** @example trace-abc */
        trace_id?: string;
        [key: string]: unknown;
      };
      /** @description Execution options and preferences */
      options?: {
        /** @default true */
        cache_result?: boolean;
        /** @default 3600 */
        cache_ttl_seconds?: number;
        /** @default false */
        notify_on_completion?: boolean;
        /** @default true */
        retry_on_failure?: boolean;
        [key: string]: unknown;
      };
    };
    ExecutionResult: {
      /** @example exec-123 */
      execution_id: string;
      /** @enum {string} */
      status: 'completed' | 'failed';
      /** @description Execution output data */
      result?: {
        [key: string]: unknown;
      };
      error?: components['schemas']['ExecutionError'];
      metadata?: {
        /** @example 1250 */
        duration_ms?: number;
        /** @example 950 */
        cpu_time_ms?: number;
        /** @example 128.5 */
        memory_used_mb?: number;
        /** @example false */
        cache_hit?: boolean;
        [key: string]: unknown;
      };
      /** Format: date-time */
      started_at: string;
      /** Format: date-time */
      completed_at?: string;
    };
    AsyncExecutionResponse: {
      /** @example exec-123 */
      execution_id: string;
      /** @enum {string} */
      status: 'pending' | 'running';
      /** @example 300 */
      estimated_duration_seconds?: number;
      /**
       * Format: uri
       * @example https://api.ossa.bluefly.io/v1/agents/agent-001/executions/exec-123
       */
      progress_url: string;
      /**
       * Format: uri
       * @example wss://api.ossa.bluefly.io/v1/agents/agent-001/executions/exec-123/progress
       */
      websocket_url?: string;
      /** Format: date-time */
      started_at: string;
    };
    ExecutionStatus: {
      execution_id: string;
      agent_id: string;
      /** @enum {string} */
      status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
      progress?: {
        percentage?: number;
        current_step?: string;
        total_steps?: number;
        /** Format: date-time */
        estimated_completion?: string;
      };
      result?: {
        [key: string]: unknown;
      };
      error?: components['schemas']['ExecutionError'];
      logs?: components['schemas']['ExecutionLogEntry'][];
      metadata?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      started_at: string;
      /** Format: date-time */
      completed_at?: string;
    };
    ExecutionError: {
      /** @example VALIDATION_FAILED */
      code: string;
      /** @example Input validation failed for required field 'data_source' */
      message: string;
      details?: {
        [key: string]: unknown;
      };
      /** @description Stack trace for debugging (only in development mode) */
      stack_trace?: string;
      /** @example corr-789 */
      correlation_id?: string;
    };
    ExecutionLogEntry: {
      /** Format: date-time */
      timestamp: string;
      /** @enum {string} */
      level: 'debug' | 'info' | 'warn' | 'error';
      message: string;
      data?: {
        [key: string]: unknown;
      };
    };
    ExecutionValidationError: {
      /** @example Execution validation failed */
      error: string;
      validation_errors: {
        /** @example input.data_source */
        field?: string;
        /** @example REQUIRED */
        code?: string;
        /** @example Field is required */
        message?: string;
        /** @description The invalid value that was provided */
        value?: unknown;
      }[];
      /** @example process_data */
      operation?: string;
      /**
       * @example [
       *   "data-processing",
       *   "validation"
       * ]
       */
      agent_capabilities?: string[];
    };
    JsonPatchOperation: OneOf<
      [
        {
          /** @enum {string} */
          op: 'add' | 'replace' | 'test';
          /** @description JSON Pointer path */
          path: string;
          /** @description Value for operation */
          value: string | number | boolean | Record<string, never> | unknown[] | null;
        },
        {
          /** @enum {string} */
          op: 'move' | 'copy';
          /** @description JSON Pointer path */
          path: string;
          /** @description Source path for operation */
          from: string;
        },
        {
          /** @enum {string} */
          op: 'remove';
          /** @description JSON Pointer path */
          path: string;
        }
      ]
    >;
    OpenAPISpecification: {
      /** @example user-api */
      id: string;
      /** @example User Management API */
      name: string;
      /** @example API for managing user accounts and profiles */
      description?: string;
      /** @description The actual OpenAPI specification content */
      content: {
        [key: string]: unknown;
      };
      /** @enum {string} */
      validation_status: 'valid' | 'invalid' | 'warning' | 'unknown';
      validation_errors?: {
        path?: string;
        message?: string;
        /** @enum {string} */
        severity?: 'error' | 'warning' | 'info';
      }[];
      /** @example 3.1.0 */
      version: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    SpecificationListResponse: {
      specifications: components['schemas']['OpenAPISpecification'][];
      pagination: components['schemas']['PaginationInfo'];
    };
    AgentCreatedEvent: {
      /** @constant */
      event_type: 'agent.created';
      /** Format: uuid */
      event_id: string;
      /** Format: date-time */
      timestamp: string;
      agent: components['schemas']['Agent'];
      organization_id?: string;
      user_id?: string;
    };
    AgentStatusEvent: {
      /** @constant */
      event_type: 'agent.status_changed';
      /** Format: uuid */
      event_id: string;
      /** Format: date-time */
      timestamp: string;
      agent_id: string;
      previous_status: components['schemas']['AgentStatus'];
      new_status: components['schemas']['AgentStatus'];
      /** @description Reason for status change */
      reason?: string;
      organization_id?: string;
      user_id?: string;
    };
    ExecutionCompletedEvent: {
      /** @constant */
      event_type: 'execution.completed';
      /** Format: uuid */
      event_id: string;
      /** Format: date-time */
      timestamp: string;
      execution_id: string;
      agent_id: string;
      /** @enum {string} */
      status: 'completed' | 'failed';
      duration_ms: number;
      result?: {
        [key: string]: unknown;
      };
      error?: components['schemas']['ExecutionError'];
      organization_id?: string;
      user_id?: string;
    };
    ErrorResponse: {
      /** @description Error type/code */
      error: string;
      /** @description Human-readable error message */
      message: string;
      /** @description Additional error details */
      details?: {
        [key: string]: unknown;
      };
      /** @description Unique identifier for this error instance */
      correlation_id: string;
      /** Format: date-time */
      timestamp: string;
      /** @description API path where error occurred */
      path?: string;
    };
    ValidationError: components['schemas']['ErrorResponse'] & {
      validation_errors?: {
        /** @description Field that failed validation */
        field: string;
        /** @description Validation error code */
        code: string;
        /** @description Field-specific error message */
        message: string;
        /** @description The invalid value */
        value?: unknown;
      }[];
    };
    ConflictError: components['schemas']['ErrorResponse'] & {
      conflicting_resource?: {
        /** @example agent */
        type?: string;
        /** @example agent-001 */
        id?: string;
        /** @example Existing Agent */
        name?: string;
      };
    };
    PatchError: components['schemas']['ErrorResponse'] & {
      failed_operations?: {
        operation_index?: number;
        operation?: components['schemas']['JsonPatchOperation'];
        error?: string;
      }[];
    };
  };
  responses: {
    /** @description Bad request - invalid input parameters */
    BadRequest: {
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Unauthorized - authentication required */
    Unauthorized: {
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Forbidden - insufficient permissions */
    Forbidden: {
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Resource not found */
    NotFound: {
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Validation failed */
    ValidationError: {
      content: {
        'application/json': components['schemas']['ValidationError'];
      };
    };
    /** @description Too many requests - rate limit exceeded */
    TooManyRequests: {
      headers: {
        /** @description The rate limit ceiling for that given request */
        'X-RateLimit-Limit'?: number;
        /** @description The number of requests left for the time window */
        'X-RateLimit-Remaining'?: number;
        /** @description The time at which the rate limit resets (Unix timestamp) */
        'X-RateLimit-Reset'?: number;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Internal server error */
    InternalServerError: {
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
  };
  parameters: {
    /**
     * @description Unique identifier for the agent
     * @example agent-001
     */
    AgentIdParam: string;
    /**
     * @description Unique identifier for the execution
     * @example exec-123
     */
    ExecutionIdParam: string;
    /**
     * @description Unique identifier for the specification
     * @example user-api
     */
    SpecIdParam: string;
    /**
     * @description Page number for pagination (1-based)
     * @example 1
     */
    PageParam?: number;
    /**
     * @description Number of items per page
     * @example 20
     */
    LimitParam?: number;
    /**
     * @description Sort order for results
     * @example name
     */
    SortParam?: 'created_at' | 'updated_at' | 'name' | 'status' | 'type';
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * List all agents
   * @description Retrieve a paginated list of agents with advanced filtering and sorting capabilities.
   *
   * Supports:
   * - Type-based filtering with inheritance hierarchy
   * - Capability-based search with fuzzy matching
   * - Status filtering (active, inactive, error, deploying)
   * - Creation date range queries
   * - Performance metric filtering
   */
  listAgents: {
    parameters: {
      query?: {
        page?: components['parameters']['PageParam'];
        limit?: components['parameters']['LimitParam'];
        sort?: components['parameters']['SortParam'];
        /** @description Filter by agent type (supports inheritance) */
        type?: components['schemas']['AgentType'];
        /** @description Filter by agent status */
        status?: components['schemas']['AgentStatus'][];
        /** @description Filter by required capabilities (AND logic) */
        capabilities?: string[];
        /** @description Filter agents created after this timestamp */
        created_after?: string;
        /** @description Minimum performance score (0-100) */
        performance_min?: number;
      };
    };
    responses: {
      /** @description List of agents retrieved successfully */
      200: {
        content: {
          'application/json': components['schemas']['AgentListResponse'];
          'application/yaml': components['schemas']['AgentListResponse'];
          'text/csv': string;
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Create a new agent
   * @description Create a new agent with comprehensive validation and automatic capability inference.
   *
   * Features:
   * - **Polymorphic agent types** with discriminator-based validation
   * - **Automatic capability detection** from provided specifications
   * - **Version conflict resolution** with semantic versioning
   * - **Dependency validation** against existing agents
   * - **Resource quota enforcement** per organization
   * - **Async creation** with webhook notifications
   */
  createAgent: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAgentRequest'];
        'application/yaml': components['schemas']['CreateAgentRequest'];
        'multipart/form-data': {
          agent_data?: components['schemas']['CreateAgentRequest'];
          /**
           * Format: binary
           * @description OpenAPI specification file
           */
          specification_file?: string;
          /**
           * Format: binary
           * @description Optional Dockerfile for containerized agents
           */
          dockerfile?: string;
        };
      };
    };
    responses: {
      /** @description Agent created successfully */
      201: {
        content: {
          'application/json': components['schemas']['Agent'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      /** @description Agent with this name already exists */
      409: {
        content: {
          'application/json': components['schemas']['ConflictError'];
        };
      };
      /** @description Validation failed */
      422: {
        content: {
          'application/json': components['schemas']['ValidationError'];
        };
      };
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Get agent details
   * @description Retrieve detailed information about a specific agent including:
   * - Current status and health metrics
   * - Performance statistics and SLA compliance
   * - Capability matrix and dependencies
   * - Recent execution history
   * - Configuration and metadata
   */
  getAgent: {
    parameters: {
      query?: {
        /** @description Additional data to include in response */
        include?: ('metrics' | 'history' | 'dependencies' | 'logs')[];
      };
      path: {
        agent_id: components['parameters']['AgentIdParam'];
      };
    };
    responses: {
      /** @description Agent details retrieved successfully */
      200: {
        content: {
          'application/json': components['schemas']['Agent'];
          'application/yaml': components['schemas']['Agent'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Update agent
   * @description Update an existing agent with full replacement semantics.
   *
   * Supports:
   * - **Atomic updates** with rollback on failure
   * - **Version-aware updates** with optimistic locking
   * - **Capability migration** with backwards compatibility
   * - **Hot updates** for non-breaking changes
   * - **Blue-green deployment** for breaking changes
   */
  updateAgent: {
    parameters: {
      path: {
        agent_id: components['parameters']['AgentIdParam'];
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAgentRequest'];
      };
    };
    responses: {
      /** @description Agent updated successfully */
      200: {
        content: {
          'application/json': components['schemas']['Agent'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description Version conflict detected */
      409: {
        content: {
          'application/json': components['schemas']['ConflictError'];
        };
      };
      422: components['responses']['ValidationError'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Delete agent
   * @description Delete an agent with comprehensive cleanup and dependency management.
   *
   * Features:
   * - **Graceful shutdown** with configurable timeout
   * - **Dependency validation** to prevent orphaned workflows
   * - **Data retention policies** with configurable periods
   * - **Audit trail preservation** for compliance
   * - **Cascading deletion** of related resources
   */
  deleteAgent: {
    parameters: {
      query?: {
        /** @description Force deletion even if agent has active dependencies */
        force?: boolean;
        /** @description Days to retain agent data after deletion */
        retention_days?: number;
      };
      path: {
        agent_id: components['parameters']['AgentIdParam'];
      };
    };
    responses: {
      /** @description Agent deleted successfully */
      204: {
        content: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description Cannot delete agent due to dependencies */
      409: {
        content: {
          'application/json': {
            /** @example Cannot delete agent due to active dependencies */
            error?: string;
            dependencies?: {
              /** @enum {string} */
              type?: 'workflow' | 'orchestration' | 'subscription';
              id?: string;
              name?: string;
            }[];
          };
        };
      };
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Partially update agent
   * @description Perform partial updates to an agent using JSON Patch (RFC 6902) operations.
   *
   * Supports atomic patch operations:
   * - `add` - Add new properties or array elements
   * - `remove` - Remove properties or array elements
   * - `replace` - Replace existing values
   * - `move` - Move values within the document
   * - `copy` - Copy values within the document
   * - `test` - Test values before applying other operations
   */
  patchAgent: {
    parameters: {
      path: {
        agent_id: components['parameters']['AgentIdParam'];
      };
    };
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['JsonPatchOperation'][];
      };
    };
    responses: {
      /** @description Agent patched successfully */
      200: {
        content: {
          'application/json': components['schemas']['Agent'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description Patch operation failed */
      422: {
        content: {
          'application/json': components['schemas']['PatchError'];
        };
      };
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Execute agent operation
   * @description Execute a specific operation on an agent with comprehensive input validation
   * and execution tracking.
   *
   * Execution Features:
   * - **Input schema validation** against agent capabilities
   * - **Execution context isolation** for security
   * - **Real-time progress tracking** via WebSocket
   * - **Result caching** with configurable TTL
   * - **Execution history** and audit logging
   * - **Resource quotas** and throttling
   */
  executeAgent: {
    parameters: {
      query?: {
        /** @description Execute asynchronously and return execution ID */
        async?: boolean;
        /** @description Maximum execution time in seconds */
        timeout?: number;
        /** @description Execution priority (higher numbers = higher priority) */
        priority?: number;
      };
      path: {
        agent_id: components['parameters']['AgentIdParam'];
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExecutionRequest'];
      };
    };
    responses: {
      /** @description Execution completed successfully (synchronous) */
      200: {
        content: {
          'application/json': components['schemas']['ExecutionResult'];
        };
      };
      /** @description Execution started (asynchronous) */
      202: {
        content: {
          'application/json': components['schemas']['AsyncExecutionResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description Execution validation failed */
      422: {
        content: {
          'application/json': components['schemas']['ExecutionValidationError'];
        };
      };
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Get execution status
   * @description Retrieve the status and results of an asynchronous execution.
   *
   * Provides:
   * - **Real-time status** (pending, running, completed, failed)
   * - **Progress indicators** with percentage completion
   * - **Intermediate results** for long-running operations
   * - **Resource usage metrics** (CPU, memory, duration)
   * - **Error details** with stack traces and context
   */
  getExecutionStatus: {
    parameters: {
      path: {
        agent_id: components['parameters']['AgentIdParam'];
        execution_id: components['parameters']['ExecutionIdParam'];
      };
    };
    responses: {
      /** @description Execution status retrieved successfully */
      200: {
        content: {
          'application/json': components['schemas']['ExecutionStatus'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * List OpenAPI specifications
   * @description Retrieve all OpenAPI specifications with metadata and validation status.
   *
   * Features:
   * - **Version history** tracking with semantic versioning
   * - **Validation status** against OpenAPI 3.1 schema
   * - **Dependency mapping** between specifications
   * - **Usage analytics** and adoption metrics
   */
  listSpecifications: {
    parameters: {
      query?: {
        page?: components['parameters']['PageParam'];
        limit?: components['parameters']['LimitParam'];
        /** @description Filter by OpenAPI version */
        version?: '3.0.0' | '3.0.1' | '3.0.2' | '3.0.3' | '3.1.0';
        /** @description Filter by validation status */
        status?: 'valid' | 'invalid' | 'warning' | 'unknown';
      };
    };
    responses: {
      /** @description Specifications retrieved successfully */
      200: {
        content: {
          'application/json': components['schemas']['SpecificationListResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Get specification
   * @description Retrieve a specific OpenAPI specification with full content and metadata
   */
  getSpecification: {
    parameters: {
      query?: {
        /** @description Response format */
        format?: 'json' | 'yaml';
      };
      path: {
        spec_id: components['parameters']['SpecIdParam'];
      };
    };
    responses: {
      /** @description Specification retrieved successfully */
      200: {
        content: {
          'application/json': components['schemas']['OpenAPISpecification'];
          'application/yaml': components['schemas']['OpenAPISpecification'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /**
   * Agent created notification
   * @description Triggered when a new agent is successfully created
   */
  handleAgentCreated: {
    requestBody?: {
      content: {
        'application/json': components['schemas']['AgentCreatedEvent'];
      };
    };
    responses: {
      /** @description Webhook received successfully */
      200: {
        content: never;
      };
    };
  };
  /**
   * Agent status change notification
   * @description Triggered when an agent's status changes
   */
  handleAgentStatusChanged: {
    requestBody?: {
      content: {
        'application/json': components['schemas']['AgentStatusEvent'];
      };
    };
    responses: {
      /** @description Webhook received successfully */
      200: {
        content: never;
      };
    };
  };
  /**
   * Execution completed notification
   * @description Triggered when an agent execution completes
   */
  handleExecutionCompleted: {
    requestBody?: {
      content: {
        'application/json': components['schemas']['ExecutionCompletedEvent'];
      };
    };
    responses: {
      /** @description Webhook received successfully */
      200: {
        content: never;
      };
    };
  };
}
