/**
 * Browser Exporter — Generate browser automation config from OSSA manifests.
 *
 * When an agent has browser capabilities, this generates the agent-browser
 * configuration and startup scripts.
 */

import type { OssaAgent } from '../../types/index.js';

export interface BrowserExportResult {
  files: Array<{ path: string; content: string }>;
  command: string;
}

export class BrowserExporter {
  /**
   * Export OSSA agent as a browser automation agent.
   * Generates agent-browser config and launch scripts.
   */
  export(manifest: OssaAgent): BrowserExportResult {
    const name = manifest.metadata?.name || 'ossa-browser-agent';
    const headless = true;

    const launchScript = [
      '#!/bin/bash',
      `# Browser agent: ${name}`,
      `# Generated by ossa export --format=browser-agent`,
      '',
      '# Start agent-browser in headless mode',
      `npx agent-browser --headless=${headless} \\`,
      `  --url="\${BASE_URL:-http://localhost:3000}" \\`,
      '  --timeout=30000 \\',
      '  --screenshot-on-error',
      '',
    ].join('\n');

    const dockerService = {
      [`${name}-browser`]: {
        image: 'ghcr.io/nicepkg/agent-browser:latest',
        environment: {
          HEADLESS: 'true',
          BASE_URL: '${BASE_URL:-http://localhost:3000}',
        },
        ports: ['9222:9222'],
        restart: 'unless-stopped',
      },
    };

    const dockerCompose = `# Browser automation service for ${name}
# Add to your docker-compose.yml services section
services:
  ${name}-browser:
    image: ghcr.io/nicepkg/agent-browser:latest
    environment:
      - HEADLESS=true
      - BASE_URL=\${BASE_URL:-http://localhost:3000}
    ports:
      - "9222:9222"
    restart: unless-stopped
`;

    return {
      files: [
        { path: 'scripts/browser-agent.sh', content: launchScript },
        { path: 'docker-compose.browser.yml', content: dockerCompose },
      ],
      command: `npx agent-browser --headless`,
    };
  }

  /**
   * Check if an OSSA manifest declares browser capabilities.
   */
  hasBrowserCapability(manifest: OssaAgent): boolean {
    const tools = manifest.spec?.tools || [];
    const toolNames = tools.map((t: unknown) =>
      typeof t === 'string' ? t : typeof t === 'object' && t !== null ? (t as Record<string, string>).name || '' : ''
    ).join(' ').toLowerCase();
    const role = (manifest.spec?.role || '').toLowerCase();

    return (
      toolNames.includes('browser') ||
      toolNames.includes('playwright') ||
      toolNames.includes('cdp') ||
      toolNames.includes('web-scrape') ||
      role.includes('browser') ||
      role.includes('scraper')
    );
  }
}
