/**
 * FusionInventory Agent Configuration Types
 *
 * Maps to agent.cfg key=value directives.
 * Reference: https://documentation.fusioninventory.org/FusionInventory_agent/manpage/agent.cfg/
 */

/** Generic directives from agent.cfg */
export interface FusionInventoryAgentConfig {
  // Connection
  server?: string;
  delaytime?: number;
  lazy?: boolean;
  proxy?: string;
  user?: string;
  password?: string;
  timeout?: number;

  // SSL
  'ca-cert-dir'?: string;
  'ca-cert-file'?: string;
  'no-ssl-check'?: boolean;

  // HTTP daemon
  'no-httpd'?: boolean;
  'httpd-ip'?: string;
  'httpd-port'?: number;
  'httpd-trust'?: string[];

  // Logging
  logger?: 'file' | 'stderr' | 'syslog';
  logfile?: string;
  'logfile-maxsize'?: number;
  logfacility?: string;
  color?: boolean;
  debug?: number;

  // Task control
  'no-task'?: string[];
  tag?: string;
  'no-category'?: string[];
  'additional-content'?: string;
  'scan-homedirs'?: boolean;
  force?: boolean;
  'collect-timeout'?: number;
  'no-p2p'?: boolean;
}

/** Serialise config to agent.cfg key=value format */
export function serialiseAgentCfg(cfg: FusionInventoryAgentConfig): string {
  const lines: string[] = [
    '# FusionInventory agent.cfg',
    '# Generated by OSSA (openstandardagents)',
    '',
  ];

  for (const [key, value] of Object.entries(cfg)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      lines.push(`${key} = ${value.join(',')}`);
    } else if (typeof value === 'boolean') {
      lines.push(`${key} = ${value ? '1' : '0'}`);
    } else {
      lines.push(`${key} = ${value}`);
    }
  }

  return lines.join('\n') + '\n';
}
