import { Agent } from '@/types/agent';

/**
 * Mock data for development and testing
 * Remove this file when connecting to real API
 */

export const mockAgents: Agent[] = [
  {
    gaid: 'gaid-001-customer-support-bot',
    name: 'Customer Support Bot',
    description:
      'AI-powered customer support agent with natural language understanding and multi-language support',
    version: '1.2.0',
    icon: undefined,
    trustLevel: 'verified',
    rating: 4.8,
    reviewCount: 234,
    downloadCount: 15234,
    capabilities: ['chat', 'nlp', 'sentiment-analysis', 'ticket-routing'],
    domains: ['customer-service', 'support'],
    platforms: [
      { name: 'kubernetes', deployment: 'kubernetes' },
      { name: 'docker', deployment: 'docker' },
    ],
    readme: '# Customer Support Bot\n\nA production-ready AI agent for customer support...',
    author: {
      name: 'BlueFly.io',
      avatar: undefined,
      verified: true,
    },
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-02-01T15:30:00Z',
    tags: ['customer-service', 'ai', 'nlp', 'chat'],
    metadata: {},
  },
  {
    gaid: 'gaid-002-data-pipeline-orchestrator',
    name: 'Data Pipeline Orchestrator',
    description: 'Automated data pipeline management with scheduling and monitoring capabilities',
    version: '2.0.1',
    icon: undefined,
    trustLevel: 'trusted',
    rating: 4.5,
    reviewCount: 142,
    downloadCount: 8932,
    capabilities: ['scheduling', 'etl', 'monitoring', 'alerting'],
    domains: ['data-engineering', 'automation'],
    platforms: [
      { name: 'kubernetes', deployment: 'kubernetes' },
      { name: 'docker', deployment: 'docker' },
      { name: 'lambda', deployment: 'serverless' },
    ],
    readme: '# Data Pipeline Orchestrator\n\nOrchestrate complex data pipelines...',
    author: {
      name: 'DataFlow Inc',
      avatar: undefined,
      verified: true,
    },
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-02-05T12:00:00Z',
    tags: ['data', 'etl', 'orchestration', 'pipeline'],
    metadata: {},
  },
  {
    gaid: 'gaid-003-code-review-assistant',
    name: 'Code Review Assistant',
    description: 'AI-powered code reviewer that checks for bugs, security issues, and best practices',
    version: '1.5.3',
    icon: undefined,
    trustLevel: 'verified',
    rating: 4.9,
    reviewCount: 567,
    downloadCount: 23456,
    capabilities: ['code-analysis', 'security-scan', 'best-practices', 'auto-fix'],
    domains: ['development', 'security'],
    platforms: [
      { name: 'github-actions', deployment: 'serverless' },
      { name: 'gitlab-ci', deployment: 'serverless' },
    ],
    readme: '# Code Review Assistant\n\nAutomate code reviews with AI...',
    author: {
      name: 'DevTools Corp',
      avatar: undefined,
      verified: true,
    },
    createdAt: '2023-12-10T09:00:00Z',
    updatedAt: '2024-02-06T11:00:00Z',
    tags: ['code-review', 'security', 'ci-cd', 'automation'],
    metadata: {},
  },
  {
    gaid: 'gaid-004-financial-analyst',
    name: 'Financial Data Analyst',
    description: 'Analyze financial data, generate reports, and provide investment insights',
    version: '1.0.0',
    icon: undefined,
    trustLevel: 'unverified',
    rating: 4.2,
    reviewCount: 89,
    downloadCount: 3421,
    capabilities: ['data-analysis', 'reporting', 'forecasting', 'visualization'],
    domains: ['finance', 'analytics'],
    platforms: [{ name: 'docker', deployment: 'docker' }],
    readme: '# Financial Data Analyst\n\nComprehensive financial analysis agent...',
    author: {
      name: 'FinTech Innovations',
      avatar: undefined,
      verified: false,
    },
    createdAt: '2024-02-01T14:00:00Z',
    updatedAt: '2024-02-01T14:00:00Z',
    tags: ['finance', 'analytics', 'reporting'],
    metadata: {},
  },
  {
    gaid: 'gaid-005-content-moderator',
    name: 'Content Moderation Agent',
    description: 'AI content moderator for detecting inappropriate content, spam, and policy violations',
    version: '2.1.0',
    icon: undefined,
    trustLevel: 'trusted',
    rating: 4.6,
    reviewCount: 312,
    downloadCount: 11234,
    capabilities: ['content-analysis', 'spam-detection', 'policy-enforcement'],
    domains: ['moderation', 'safety'],
    platforms: [
      { name: 'kubernetes', deployment: 'kubernetes' },
      { name: 'cloudflare-workers', deployment: 'edge' },
    ],
    readme: '# Content Moderation Agent\n\nKeep your platform safe...',
    author: {
      name: 'SafeSpace Labs',
      avatar: undefined,
      verified: true,
    },
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-02-03T16:00:00Z',
    tags: ['moderation', 'safety', 'content', 'ai'],
    metadata: {},
  },
  {
    gaid: 'gaid-006-experimental-chatbot',
    name: 'Experimental Multi-Modal Bot',
    description: 'Experimental chatbot with image, audio, and video processing capabilities',
    version: '0.3.0-alpha',
    icon: undefined,
    trustLevel: 'experimental',
    rating: 3.8,
    reviewCount: 45,
    downloadCount: 892,
    capabilities: ['chat', 'image-processing', 'audio-processing', 'video-analysis'],
    domains: ['experimental', 'multi-modal'],
    platforms: [{ name: 'docker', deployment: 'docker' }],
    readme: '# Experimental Multi-Modal Bot\n\n⚠️ Experimental - Use with caution...',
    author: {
      name: 'AI Research Lab',
      avatar: undefined,
      verified: false,
    },
    createdAt: '2024-02-05T09:00:00Z',
    updatedAt: '2024-02-06T14:00:00Z',
    tags: ['experimental', 'multi-modal', 'research'],
    metadata: {},
  },
];

export const mockStatistics = {
  totalDeployments: 67891,
  activeInstances: 15234,
  successRate: 98.5,
  avgResponseTime: 245,
  last30Days: {
    deployments: 4521,
    activeUsers: 1423,
  },
};
