<?php

declare(strict_types=1);

namespace Ossa\SymfonyBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * OSSA Bundle Configuration
 *
 * Defines configuration structure for OSSA agents in Symfony.
 */
class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('ossa');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                // Global settings
                ->scalarNode('default_provider')
                    ->defaultValue('anthropic')
                    ->info('Default LLM provider (anthropic, openai, google, azure)')
                ->end()
                ->scalarNode('default_model')
                    ->defaultValue('claude-sonnet-4-20250514')
                    ->info('Default LLM model')
                ->end()
                ->floatNode('default_temperature')
                    ->defaultValue(0.7)
                    ->min(0.0)
                    ->max(2.0)
                    ->info('Default temperature (0.0-2.0)')
                ->end()

                // Manifest loading
                ->arrayNode('manifest_paths')
                    ->info('Paths to scan for OSSA manifests')
                    ->defaultValue(['config/agents'])
                    ->scalarPrototype()->end()
                ->end()
                ->booleanNode('auto_discover')
                    ->defaultTrue()
                    ->info('Automatically discover *.ossa.yaml files')
                ->end()

                // LLM Provider configurations
                ->arrayNode('providers')
                    ->info('LLM provider API configurations')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('api_key')
                                ->info('API key (use %env(ANTHROPIC_API_KEY)% for secrets)')
                            ->end()
                            ->scalarNode('base_url')
                                ->info('Custom API base URL')
                            ->end()
                            ->integerNode('timeout')
                                ->defaultValue(60)
                                ->info('Request timeout in seconds')
                            ->end()
                            ->integerNode('max_retries')
                                ->defaultValue(3)
                                ->info('Maximum retry attempts')
                            ->end()
                            ->arrayNode('circuit_breaker')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->booleanNode('enabled')
                                        ->defaultTrue()
                                        ->info('Enable circuit breaker pattern')
                                    ->end()
                                    ->integerNode('failure_threshold')
                                        ->defaultValue(5)
                                        ->info('Number of failures before opening circuit')
                                    ->end()
                                    ->integerNode('reset_timeout')
                                        ->defaultValue(60)
                                        ->info('Seconds before attempting to close circuit')
                                    ->end()
                                    ->floatNode('backoff_multiplier')
                                        ->defaultValue(2.0)
                                        ->info('Exponential backoff multiplier')
                                    ->end()
                                    ->integerNode('initial_backoff_ms')
                                        ->defaultValue(1000)
                                        ->info('Initial backoff delay in milliseconds')
                                    ->end()
                                    ->arrayNode('fallback_providers')
                                        ->info('Fallback provider chain (provider names)')
                                        ->scalarPrototype()->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                // Observability
                ->arrayNode('observability')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable telemetry and tracing')
                        ->end()
                        ->scalarNode('otlp_endpoint')
                            ->defaultNull()
                            ->info('OpenTelemetry OTLP endpoint')
                        ->end()
                        ->enumNode('log_level')
                            ->values(['debug', 'info', 'warning', 'error'])
                            ->defaultValue('info')
                        ->end()
                    ->end()
                ->end()

                // Safety & Cost Controls
                ->arrayNode('safety')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('pii_detection')
                            ->defaultTrue()
                            ->info('Detect and redact PII')
                        ->end()
                        ->booleanNode('secrets_detection')
                            ->defaultTrue()
                            ->info('Detect and block secrets')
                        ->end()
                        ->floatNode('max_cost_per_day')
                            ->defaultNull()
                            ->info('Maximum cost per day in USD')
                        ->end()
                        ->integerNode('max_tokens_per_day')
                            ->defaultNull()
                            ->info('Maximum tokens per day')
                        ->end()
                    ->end()
                ->end()

                // Security
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('audit_logging')
                            ->defaultTrue()
                            ->info('Enable audit logging for all LLM API calls')
                        ->end()
                        ->booleanNode('enforce_https')
                            ->defaultTrue()
                            ->info('Enforce HTTPS for all provider endpoints')
                        ->end()
                        ->booleanNode('sign_requests')
                            ->defaultTrue()
                            ->info('Enable request signing where supported')
                        ->end()
                        ->scalarNode('audit_log_channel')
                            ->defaultValue('ossa_audit')
                            ->info('Monolog channel for audit logs')
                        ->end()
                    ->end()
                ->end()

                // Rate Limiting
                ->arrayNode('rate_limit')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Enable rate limiting')
                        ->end()
                        ->arrayNode('user')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('limit')
                                    ->defaultValue(100)
                                    ->info('Maximum requests per user per window')
                                ->end()
                                ->scalarNode('interval')
                                    ->defaultValue('1 hour')
                                    ->info('Time window (e.g., "1 hour", "1 day")')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('global')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('limit')
                                    ->defaultValue(1000)
                                    ->info('Maximum requests globally per window')
                                ->end()
                                ->scalarNode('interval')
                                    ->defaultValue('1 hour')
                                    ->info('Time window (e.g., "1 hour", "1 day")')
                                ->end()
                            ->end()
                        ->end()
                        ->scalarNode('storage')
                            ->defaultValue('cache.app')
                            ->info('Storage service for rate limiter (e.g., cache.app, redis.cache)')
                        ->end()
                    ->end()
                ->end()

                // Caching
                ->arrayNode('cache')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Enable response caching')
                        ->end()
                        ->integerNode('response_ttl')
                            ->defaultValue(3600)
                            ->info('Response cache TTL in seconds (default: 1 hour)')
                        ->end()
                        ->integerNode('manifest_ttl')
                            ->defaultValue(86400)
                            ->info('Manifest cache TTL in seconds (default: 24 hours)')
                        ->end()
                        ->scalarNode('pool')
                            ->defaultValue('cache.app')
                            ->info('Cache pool service (e.g., cache.app, redis.cache)')
                        ->end()
                    ->end()
                ->end()

                // Agent Definitions
                ->arrayNode('agents')
                    ->info('Inline agent definitions')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('manifest')
                                ->info('Path to OSSA manifest file')
                            ->end()
                            ->scalarNode('role')
                                ->info('Agent role/purpose')
                            ->end()
                            ->arrayNode('llm')
                                ->children()
                                    ->scalarNode('provider')->end()
                                    ->scalarNode('model')->end()
                                    ->floatNode('temperature')->end()
                                ->end()
                            ->end()
                            ->arrayNode('tools')
                                ->scalarPrototype()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                // MCP Tools
                ->arrayNode('mcp')
                    ->info('MCP (Model Context Protocol) tool servers')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                        ->end()
                        ->arrayNode('servers')
                            ->useAttributeAsKey('name')
                            ->arrayPrototype()
                                ->children()
                                    ->enumNode('transport')
                                        ->values(['stdio', 'sse', 'websocket'])
                                        ->isRequired()
                                    ->end()
                                    ->scalarNode('command')->end()
                                    ->arrayNode('args')
                                        ->scalarPrototype()->end()
                                    ->end()
                                    ->scalarNode('url')->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
