/**
 * OSSA Scaffold Command
 * Scaffold complete agent structure with all directories and files
 *
 * Creates:
 *   .agents/<agent-name>/
 *     ├── manifest.ossa.yaml
 *     ├── prompts/
 *     ├── tools/
 *     └── README.md
 *
 * SOLID Principles:
 * - Single Responsibility: Only scaffolds agent structure
 * - Uses shared utilities (DRY)
 */

import { Command } from 'commander';
import chalk from 'chalk';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';
import { getVersion, getApiVersion } from '../../utils/version.js';
import { handleCommandError } from '../utils/index.js';
import type { OssaAgent } from '../../types/index.js';

export const scaffoldCommand = new Command('scaffold')
  .description('Scaffold complete agent structure with directories and files')
  .argument('<name>', 'Agent name (DNS-1123 format)')
  .option('-d, --description <desc>', 'Agent description')
  .option('-r, --role <role>', 'Agent role/system prompt')
  .option('-p, --provider <provider>', 'LLM provider (openai, anthropic, google)', 'openai')
  .option('-m, --model <model>', 'LLM model name')
  .option('-o, --output <dir>', 'Output directory', '.agents')
  .option('--with-prompts', 'Create prompts/ directory')
  .option('--with-tools', 'Create tools/ directory')
  .option('--with-readme', 'Create README.md')
  .option('-f, --force', 'Overwrite existing files')
  .action(async (name: string, options) => {
    try {
      const agentId = name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
      const outputDir = path.resolve(process.cwd(), options.output);
      const agentDir = path.join(outputDir, agentId);

      // Validate agent name
      if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(agentId)) {
        console.log(chalk.red('✗ Invalid agent name'));
        console.log(chalk.gray('  Agent name must be DNS-1123 compliant (lowercase alphanumeric with hyphens)'));
        process.exit(1);
      }

      // Check if directory exists
      if (fs.existsSync(agentDir) && !options.force) {
        console.log(chalk.yellow(`⚠ Agent directory already exists: ${agentDir}`));
        console.log(chalk.gray('  Use --force to overwrite'));
        process.exit(1);
      }

      console.log(chalk.blue(`Scaffolding agent: ${agentId}`));
      console.log(chalk.gray('─'.repeat(50)));

      // Create agent directory
      fs.mkdirSync(agentDir, { recursive: true });
      console.log(chalk.gray(`  Created ${agentDir}/`));

      // Create manifest
      const defaultModel = options.provider === 'openai' ? 'gpt-4' :
        options.provider === 'anthropic' ? 'claude-3-5-sonnet-20241022' :
        'gemini-pro';

      const manifest: OssaAgent = {
        apiVersion: getApiVersion(),
        kind: 'Agent',
        metadata: {
          name: agentId,
          version: '1.0.0',
          description: options.description || `${name} - OSSA-compliant agent`,
        },
        spec: {
          role: options.role || `You are ${name}, a helpful AI agent.`,
          llm: {
            provider: options.provider,
            model: options.model || defaultModel,
          },
          tools: [],
        },
      };

      const manifestPath = path.join(agentDir, 'manifest.ossa.yaml');
      const manifestContent = yaml.stringify(manifest, {
        indent: 2,
        lineWidth: 0,
      });
      fs.writeFileSync(
        manifestPath,
        `# OSSA Agent Manifest\n# Generated by ossa scaffold\n\n${manifestContent}`
      );
      console.log(chalk.gray(`  Created manifest.ossa.yaml`));

      // Create prompts directory
      if (options.withPrompts) {
        const promptsDir = path.join(agentDir, 'prompts');
        fs.mkdirSync(promptsDir, { recursive: true });
        console.log(chalk.gray(`  Created prompts/`));

        // Create example prompt file
        const examplePrompt = `# Agent Prompts

## System Prompt
\`\`\`
${manifest.spec.role}
\`\`\`

## Example Prompts
- "What can you help me with?"
- "How do you work?"
`;
        fs.writeFileSync(path.join(promptsDir, 'README.md'), examplePrompt);
        console.log(chalk.gray(`  Created prompts/README.md`));
      }

      // Create tools directory
      if (options.withTools) {
        const toolsDir = path.join(agentDir, 'tools');
        fs.mkdirSync(toolsDir, { recursive: true });
        console.log(chalk.gray(`  Created tools/`));

        // Create example tool file
        const exampleTool = `# Agent Tools

## Tool Definitions

Add your tool definitions here. Tools can be:
- MCP servers
- API endpoints
- Custom functions

Example:
\`\`\`yaml
tools:
  - name: example-tool
    description: An example tool
    type: function
\`\`\`
`;
        fs.writeFileSync(path.join(toolsDir, 'README.md'), exampleTool);
        console.log(chalk.gray(`  Created tools/README.md`));
      }

      // Create README
      if (options.withReadme) {
        const readmeContent = `# ${name}

${options.description || `${name} - OSSA-compliant agent`}

## Overview

This agent is defined using the OSSA (Open Standard for Scalable AI Agents) specification.

## Manifest

See \`manifest.ossa.yaml\` for the complete agent definition.

## Structure

\`\`\`
${agentId}/
├── manifest.ossa.yaml    # OSSA agent manifest
${options.withPrompts ? '├── prompts/              # Agent prompts\n' : ''}${options.withTools ? '├── tools/                # Agent tools\n' : ''}└── README.md             # This file
\`\`\`

## Usage

Validate the manifest:
\`\`\`bash
ossa validate manifest.ossa.yaml
\`\`\`

## Version

- OSSA Version: ${getApiVersion()}
- Agent Version: ${manifest.metadata.version}
`;
        fs.writeFileSync(path.join(agentDir, 'README.md'), readmeContent);
        console.log(chalk.gray(`  Created README.md`));
      }

      console.log('');
      console.log(chalk.green('✓ Agent scaffolded successfully'));
      console.log('');
      console.log(chalk.blue('Next steps:'));
      console.log(chalk.gray(`  1. Edit ${path.relative(process.cwd(), manifestPath)}`));
      console.log(chalk.gray('  2. Run `ossa validate manifest.ossa.yaml` to validate'));
      if (!options.withReadme) {
        console.log(chalk.gray('  3. Optionally add README.md with --with-readme'));
      }

      process.exit(0);
    } catch (error) {
      handleCommandError(error);
    }
  });
