import { OssaAgent } from '@bluefly/openstandardagents';

export type SdkLanguage = 'typescript' | 'python';

export class SdkGenerator {
  /**
   * Generate SDK code for a given OSSA Agent Manifest
   */
  public generate(manifest: OssaAgent, language: SdkLanguage): string {
    switch (language) {
      case 'typescript':
        return this.generateTypeScript(manifest);
      case 'python':
        return this.generatePython(manifest);
      default:
        throw new Error(`Unsupported language: ${language}`);
    }
  }

  private generateTypeScript(manifest: OssaAgent): string {
    const name = this.toPascalCase(manifest.metadata?.name || 'Agent');
    const description = manifest.metadata?.description || '';
    const tools = manifest.spec?.tools || [];
    const messages = manifest.spec?.messaging?.commands || [];

    const methods = [
      ...tools.map((t) => this.generateTsToolMethod(t)),
      ...messages.map((m) => this.generateTsCommandMethod(m)),
    ].join('\n\n');

    return `
/**
 * ${name} SDK
 * ${description}
 * Auto-generated by OSSA SDK Codegen
 */

import { AgentClient, AgentConfig } from '@bluefly/ossa-client';

export class ${name} extends AgentClient {
  constructor(config: AgentConfig) {
    super(config);
  }

  ${methods}
}
`;
  }

  private generateTsToolMethod(tool: { name?: string; [key: string]: unknown }): string {
    const toolName = this.toCamelCase(tool.name || 'tool');
    // Simplified type handling for prototype
    return `  /**
   * Execute tool: ${tool.name}
   */
  public async ${toolName}(params: Record<string, unknown>): Promise<unknown> {
    return this.executeTool('${tool.name}', params);
  }`;
  }

  private generateTsCommandMethod(command: { name?: string; description?: string; [key: string]: unknown }): string {
    const cmdName = this.toCamelCase(command.name || 'command');
    return `  /**
   * Send command: ${command.name}
   * ${command.description || ''}
   */
  public async ${cmdName}(payload: Record<string, unknown>): Promise<unknown> {
    return this.sendCommand('${command.name}', payload);
  }`;
  }

  private generatePython(manifest: OssaAgent): string {
    const name = this.toPascalCase(manifest.metadata?.name || 'Agent');
    const description = manifest.metadata?.description || '';
    const tools = manifest.spec?.tools || [];
    const messages = manifest.spec?.messaging?.commands || [];

    const methods = [
      ...tools.map((t) => this.generatePyToolMethod(t)),
      ...messages.map((m) => this.generatePyCommandMethod(m)),
    ].join('\n\n');

    return `
"""
${name} SDK
${description}
Auto-generated by OSSA SDK Codegen
"""

from ossa.client import AgentClient, AgentConfig
from typing import Any, Dict

class ${name}(AgentClient):
    def __init__(self, config: AgentConfig):
        super().__init__(config)

${methods}
`;
  }

  private generatePyToolMethod(tool: { name?: string; [key: string]: unknown }): string {
    const toolName = this.toSnakeCase(tool.name || 'tool');
    return `    def ${toolName}(self, params: Dict[str, Any]) -> Any:
        """
        Execute tool: ${tool.name}
        """
        return self.execute_tool('${tool.name}', params)`;
  }

  private generatePyCommandMethod(command: { name?: string; description?: string; [key: string]: unknown }): string {
    const cmdName = this.toSnakeCase(command.name || 'command');
    return `    def ${cmdName}(self, payload: Dict[str, Any]) -> Any:
        """
        Send command: ${command.name}
        ${command.description || ''}
        """
        return self.send_command('${command.name}', payload)`;
  }

  // Utils
  private toPascalCase(str: string): string {
    return str.replace(/(^\w|-\w)/g, (g) => g.replace('-', '').toUpperCase());
  }

  private toCamelCase(str: string): string {
    return str.replace(/-\w/g, (g) => g[1].toUpperCase());
  }

  private toSnakeCase(str: string): string {
    return str.replace(/-/g, '_').toLowerCase();
  }
}