import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Primary Brand Color - Deep Purple
        primary: {
          DEFAULT: 'var(--ossa-primary)',
          50: 'var(--ossa-primary-50)',
          100: 'var(--ossa-primary-100)',
          200: 'var(--ossa-primary-200)',
          300: 'var(--ossa-primary-300)',
          400: 'var(--ossa-primary-400)',
          500: 'var(--ossa-primary)',
          600: 'var(--ossa-primary-600)',
          700: 'var(--ossa-primary-700)',
          800: 'var(--ossa-primary-800)',
          900: 'var(--ossa-primary-900)',
          950: 'var(--ossa-primary-950)',
        },
        // Secondary Brand Color - Cyan Blue
        secondary: {
          DEFAULT: 'var(--ossa-secondary)',
          50: 'var(--ossa-secondary-50)',
          100: 'var(--ossa-secondary-100)',
          200: 'var(--ossa-secondary-200)',
          300: 'var(--ossa-secondary-300)',
          400: 'var(--ossa-secondary-400)',
          500: 'var(--ossa-secondary)',
          600: 'var(--ossa-secondary-600)',
          700: 'var(--ossa-secondary-700)',
          800: 'var(--ossa-secondary-800)',
          900: 'var(--ossa-secondary-900)',
          950: 'var(--ossa-secondary-950)',
        },
        // Accent Color - Light Purple
        accent: {
          DEFAULT: 'var(--ossa-accent)',
          50: 'var(--ossa-accent-50)',
          100: 'var(--ossa-accent-100)',
          200: 'var(--ossa-accent-200)',
          300: 'var(--ossa-accent-300)',
          400: 'var(--ossa-accent-400)',
          500: 'var(--ossa-accent)',
          600: 'var(--ossa-accent-600)',
          700: 'var(--ossa-accent-700)',
          800: 'var(--ossa-accent-800)',
          900: 'var(--ossa-accent-900)',
          950: 'var(--ossa-accent-950)',
        },
        // Dark Purple - For contrast and depth
        'dark-purple': {
          DEFAULT: 'var(--ossa-dark-purple)',
          50: 'var(--ossa-dark-purple-50)',
          100: 'var(--ossa-dark-purple-100)',
          200: 'var(--ossa-dark-purple-200)',
          300: 'var(--ossa-dark-purple-300)',
          400: 'var(--ossa-dark-purple-400)',
          500: 'var(--ossa-dark-purple-500)',
          600: 'var(--ossa-dark-purple-600)',
          700: 'var(--ossa-dark-purple-700)',
          800: 'var(--ossa-dark-purple-800)',
          900: 'var(--ossa-dark-purple)',
          950: 'var(--ossa-dark-purple-950)',
        },
        // Semantic Colors - Success, Warning, Error, Info
        success: {
          DEFAULT: 'var(--ossa-success)',
          50: 'var(--ossa-success-50)',
          100: 'var(--ossa-success-100)',
          200: 'var(--ossa-success-200)',
          300: 'var(--ossa-success-300)',
          400: 'var(--ossa-success-400)',
          500: 'var(--ossa-success)',
          600: 'var(--ossa-success-600)',
          700: 'var(--ossa-success-700)',
          800: 'var(--ossa-success-800)',
          900: 'var(--ossa-success-900)',
          950: 'var(--ossa-success-950)',
        },
        warning: {
          DEFAULT: 'var(--ossa-warning)',
          50: 'var(--ossa-warning-50)',
          100: 'var(--ossa-warning-100)',
          200: 'var(--ossa-warning-200)',
          300: 'var(--ossa-warning-300)',
          400: 'var(--ossa-warning-400)',
          500: 'var(--ossa-warning)',
          600: 'var(--ossa-warning-600)',
          700: 'var(--ossa-warning-700)',
          800: 'var(--ossa-warning-800)',
          900: 'var(--ossa-warning-900)',
          950: 'var(--ossa-warning-950)',
        },
        error: {
          DEFAULT: 'var(--ossa-error)',
          50: 'var(--ossa-error-50)',
          100: 'var(--ossa-error-100)',
          200: 'var(--ossa-error-200)',
          300: 'var(--ossa-error-300)',
          400: 'var(--ossa-error-400)',
          500: 'var(--ossa-error)',
          600: 'var(--ossa-error-600)',
          700: 'var(--ossa-error-700)',
          800: 'var(--ossa-error-800)',
          900: 'var(--ossa-error-900)',
          950: 'var(--ossa-error-950)',
        },
        info: {
          DEFAULT: 'var(--ossa-info)',
          50: 'var(--ossa-info-50)',
          100: 'var(--ossa-info-100)',
          200: 'var(--ossa-info-200)',
          300: 'var(--ossa-info-300)',
          400: 'var(--ossa-info-400)',
          500: 'var(--ossa-info)',
          600: 'var(--ossa-info-600)',
          700: 'var(--ossa-info-700)',
          800: 'var(--ossa-info-800)',
          900: 'var(--ossa-info-900)',
          950: 'var(--ossa-info-950)',
        },
        // Neutral Grays
        gray: {
          50: 'var(--ossa-gray-50)',
          100: 'var(--ossa-gray-100)',
          200: 'var(--ossa-gray-200)',
          300: 'var(--ossa-gray-300)',
          400: 'var(--ossa-gray-400)',
          500: 'var(--ossa-gray-500)',
          600: 'var(--ossa-gray-600)',
          700: 'var(--ossa-gray-700)',
          800: 'var(--ossa-gray-800)',
          900: 'var(--ossa-gray-900)',
          950: 'var(--ossa-gray-950)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'Courier New', 'monospace'],
        body: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        heading: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        code: ['JetBrains Mono', 'Menlo', 'Monaco', 'Courier New', 'monospace'],
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: '#334155',
            a: {
              color: '#0284c7',
              '&:hover': {
                color: '#0369a1',
              },
            },
          },
        },
      },
    },
  },
  plugins: [],
};

export default config;
